openapi: 3.1.0
info:
  title: aba-applyCard
  description: ''
  version: 1.0.0
tags: [ ]
paths:
  /ams/api/v1/aba/cards/applyCard:
    get:
      summary: applyCard
      deprecated: false
      description: ''
      tags: [ ]
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayApplyCardRequest'
            examples: { }
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayApplyCardResponse'
          headers: { }
      security: [ ]
webhooks: { }
components:
  schemas:
    CardLimitInfo:
      type: object
      properties:
        currency:
          type: string
        dailyLimitMax:
          type: string
        monthlyLimitMax:
          type: string
        perTransactionLimitMax:
          type: string
        perCardLimitMax:
          type: string
    AuthorizationControl:
      type: object
      properties:
        cardActiveTime:
          type: string
        cardCancelTime:
          type: string
        allowedMerchantCategoryList:
          type: array
          items:
            type: string
        allowedAuthTimes:
          type: string
        allowedCurrencies:
          type: string
        cardLimitInfo:
          $ref: '#/components/schemas/CardLimitInfo'
    AlipayApplyCardRequest:
      type: object
      properties:
        requestId:
          type: string
        cardNickName:
          type: string
        cardBinRule:
          type: string
        purpose:
          type: string
        metadata:
          type: object
          properties: { }
          additionalProperties:
            type: string
        authorizationControl:
          $ref: '#/components/schemas/AuthorizationControl'
        note:
          type: string
    ResultStatusType:
      type: string
      enum:
        - S
        - F
        - U
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: |
            The result status. Valid values are:

            S: indicates that the result status is successful.
            F: indicates that the result status is failed. 
            U: indicates that the result status is unknown. 
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: The result message.
      required:
        - resultCode
        - resultStatus
    AlipayApplyCardResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
        requestId:
          type: string
        status:
          type: string
        assetId:
          type: string
        cvv:
          type: string
        cardNo:
          type: string
        expiredMonth:
          type: string
        expiredYear:
          type: string
      required:
        - result
  securitySchemes: { }
servers:
  - url: https://open-sea-global.alipay.com/ams/api/v1/aba/cards/applyCard