openapi: 3.1.0
info:
  title: authorizations_applyToken
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/authorizations/applyToken:
    post:
      summary: applyToken
      deprecated: false
      description: >
        Use this API to get the cashier page address. After getting the cashier
        page address, you can redirect the user to the cashier page to make a
        payment.
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayAuthApplyTokenRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayAuthApplyTokenResponse'
          headers: {}
      security: []
components:
  schemas:
    PspCustomerInfo:
      type: object
      properties:
        pspName:
          type: string
        pspCustomerId:
          type: string
        displayCustomerId:
          type: string
        displayCustomerName:
          type: string
        customer2088Id:
          type: string
        extendInfo:
          type: string
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: |-
            The result status. Valid values are:

            S: indicates that the result status is successful.
            F: indicates that the result status is failed. 
            U: indicates that the result status is unknown. 
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: The result message.
      required:
        - resultCode
        - resultStatus
        - resultMessage
    ResultStatusType:
      type:
        - string
        - 'null'
      enum:
        - S
        - F
        - U
    CustomerBelongsTo:
      type: string
      enum:
        - RABBIT_LINE_PAY
        - TRUEMONEY
        - ALIPAY_HK
        - TNG
        - ALIPAY_CN
        - GCASH
        - DANA
        - KAKAOPAY
        - BKASH
        - EASYPAISA
        - PAYPAY
        - BOOST
        - GRABPAY_MY
        - MAYA
        - GRABPAY_PH
        - GRABPAY_SG
        - NAVERPAY
        - JKOPAY
        - KPLUS
        - DIRECT_DEBIT_SIAMCOMMERCIALBANK
        - DIRECT_DEBIT_KRUNGTHAIBANK
        - ZALOPAY
        - DIRECTDEBIT_YAPILY
        - TOSSPAY
        - MOMO
        - ANTOM_BIZ_ACCOUNT
    GrantType:
      type: string
      enum:
        - AUTHORIZATION_CODE
        - REFRESH_TOKEN
    AlipayAuthApplyTokenRequest:
      type: object
      properties:
        grantType:
          $ref: '#/components/schemas/GrantType'
          description: >-
            The task to complete by using this API. Valid values are:  


            AUTHORIZATION_CODE: When you want to get the access token, use this
            value. You can get an access token after calling this API
            successfully.

            REFRESH_TOKEN: Each access token has an expiry time that is
            specified by accessTokenExpiryTime. When your access token is about
            to expire and you want to get a new access token, use this value.
            You can get a new access token after calling this API successfully. 
        customerBelongsTo:
          $ref: '#/components/schemas/CustomerBelongsTo'
          description: >-
            The wallet that the customer uses. See Payment methods to check the
            valid values.  


            More information:


            Maximum length: 64 characters
        authCode:
          type: string
          description: >-
            The authorization code, used for getting an access token. The value
            of this field is obtained from the reconstructed redirection URL
            returned by the wallet.


            Note: Specify this field when the value of grantType is
            AUTHORIZATION_CODE.


            More information:


            Maximum length: 128 characters
        refreshToken:
          type: string
          description: >-
            The refresh token, used for getting a new access token when the
            access token is about to expire. The refresh token is obtained from
            the response of the successfully called applyToken API.


            Note: Specify this field when the value of grantType is
            REFRESH_TOKEN.


            More information:


            Maximum length: 128 characters
        extendInfo:
          type: string
        merchantRegion:
          type: string
          description: >-
            The country or region where the merchant or secondary merchant
            operates the business. The parameter is a 2-letter country/region
            code that follows ISO 3166 Country Codes standard. Only US, JP, PK,
            SG are supported now.


            Note: This field is required when you use the Global Acquirer
            Gateway (GAGW) product.


            More information:


            Maximum length: 2 characters
      required:
        - grantType
        - customerBelongsTo
    AlipayAuthApplyTokenResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
          description: >-
            Indicates whether this API is called successfully. If this API is
            successfully called, the access token can be obtained.
        accessToken:
          type: string
          description: >
            The access token that is used to access the corresponding scope of
            the user resource. 


            Note: This field is returned when the API is called successfully.


            More information:


            Maximum length: 128 characters
        accessTokenExpiryTime:
          type: string
          description: >
            The time after which the access token expires. After the access
            token expires, the access token cannot be used to deduct money from
            the user's account. 


            Note: This field is returned when accessToken is returned.


            More information:


            The value follows the ISO 8601 standard format. For example,
            "2019-11-27T12:01:01+08:00".
        refreshToken:
          type: string
          description: >-
            The refresh token that is used to exchange for a new access token
            when the access token is about to expire. 


            Note: This field is returned when the wallet supports refreshing the
            token. If this field is not returned, it indicates that the access
            token has a quite long valid period.


            More information:


            Maximum length: 128 characters
        refreshTokenExpiryTime:
          type: string
          description: >-
            The time after which the refresh token expires. After the refresh
            token expires, the refresh token cannot be used to retrieve a new
            access token. 


            Note: This field is returned when refreshToken is returned.


            More information:


            The value follows the ISO 8601 standard format. For example,
            "2019-11-27T12:01:01+08:00".
        extendInfo:
          type: string
          description: |-
            Extended information.

            Note: This field is returned when extended information exists.

            More information:

            Maximum length: 2048 characters
        userLoginId:
          type: string
          description: >-
            The login ID that the user used to register in the wallet. The login
            ID can be the user's email address or phone number, which is masked
            when returned to Alipay+ payment methods . This field can inform the
            merchant of the users who are registered.


            Note: This field is returned when result.resultCode is SUCCESS and
            the value of the scopes field in the consult API is AGREEMENT_PAY.


            More information:


            Maximum length: 64 characters
        pspCustomerInfo:
          $ref: '#/components/schemas/PspCustomerInfo'
      required:
        - result
  securitySchemes: {}
servers:
  - url: https://open-sea-global.alipay.com/ams/api/v1/authorizations/applyToken
    description: 正式环境
security: []
