---
openapi: 3.1.0
info:
  title: payments_capture
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/payments/capture:
    post:
      summary: capture
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                captureRequestId:
                  type: string
                  description: "The unique ID that is assigned by the merchant to\
                    \ identify a capture request. Antom uses this field for idempotence\
                    \ control.  \n\nMore information:\n\nThis field is an API idempotency\
                    \ field.For capture requests that are initiated with the same\
                    \ value of captureRequestId and reach a final status (S or F),\
                    \ the same result is to be returned for the request.\nMaximum\
                    \ length: 64 characters"
                paymentId:
                  type: string
                  description: "The unique ID that is assigned by Antom to identify\
                    \ a payment.  \n\nMore information:\n\nMaximum length: 64 characters"
                captureAmount: &id001
                  description: The capture amount that the merchant requests to receive
                    in the transaction currency.
                  $ref: '#/components/schemas/Amount'
                isLastCapture:
                  type: boolean
              required:
              - captureRequestId
              - paymentId
              - captureAmount
            example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: &id002
                    $ref: '#/components/schemas/Result'
                  captureRequestId:
                    type: string
                    description: 'The unique ID that is assigned by a merchant to
                      identify a capture request.


                      Note: This parameter is returned when the capture status is
                      successful.


                      More information:


                      Maximum length: 64 characters'
                  captureId:
                    type: string
                    description: 'The unique ID that is assigned by Antom to identify
                      a capture.


                      Note: This parameter is returned when the capture status is
                      successful.


                      More information:


                      Maximum length: 64 characters'
                  paymentId:
                    type: string
                    description: 'The unique ID that is assigned by Antom to identify
                      a payment.


                      Note: This parameter is returned when the capture status is
                      successful.


                      More information:


                      Maximum length: 64 characters'
                  captureAmount: *id001
                  captureTime:
                    type: string
                    description: "The time when Antom captures the payment. \n\nNote:\
                      \ This parameter is returned when the capture status is successful.\n\
                      \nMore information:\n\nThe value follows the ISO 8601 standard\
                      \ format. For example, \"2019-11-27T12:01:01+08:00\"."
                  acquirerReferenceNo:
                    type: string
                    description: "The unique ID assigned by the non-Antom acquirer\
                      \ for the transaction.  \n\nMore information:\n\nMaximum length:\
                      \ 64 characters"
                required:
                - result
              example:
                result:
                  resultStatus: S
                  resultCode: SUCCESS
                  resultMessage: success.
                captureTime: '2025-04-14T20:35:50-07:00'
                paymentId: 202504151940108001001889C0235018078
                captureRequestId: capture_jk02038196_20250414_203548_515
                captureId: 202504151940108070001889C0253659686
                captureAmount:
                  currency: HKD
                  value: '100'
          headers: {}
      security: []
components:
  schemas:
    AlipayCaptureRequest:
      type: object
      properties:
        captureRequestId:
          type: string
          description: "The unique ID that is assigned by the merchant to identify\
            \ a capture request. Antom uses this field for idempotence control.  \n\
            \nMore information:\n\nThis field is an API idempotency field.For capture\
            \ requests that are initiated with the same value of captureRequestId\
            \ and reach a final status (S or F), the same result is to be returned\
            \ for the request.\nMaximum length: 64 characters"
        paymentId:
          type: string
          description: "The unique ID that is assigned by Antom to identify a payment.\
            \  \n\nMore information:\n\nMaximum length: 64 characters"
        captureAmount:
          description: The capture amount that the merchant requests to receive in
            the transaction currency.
          $ref: '#/components/schemas/Amount'
        isLastCapture:
          type: boolean
        captureType:
          type: string
          description: The type of capture operation
        transit:
          $ref: '#/components/schemas/Transit'
          description: Transit related information
      required:
      - captureRequestId
      - paymentId
      - captureAmount
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: "The 3-letter currency code that follows the ISO 4217 standard.\
            \ \n\nMore information:\n\nMaximum length: 3 characters"
        value:
          type: string
          description: "The value of the amount as a positive integer in the smallest\
            \ currency unit. For example, if the currency is USD and the amount is\
            \ $1.00, set the value of this parameter to 100; or if the currency is\
            \ JPY and the amount is ￥1, set the value of this parameter to 1.  \n\n\
            For details about the smallest currency unit, see Smallest unit of the\
            \ currency .\n\nFor details about the minimum payment amount allowed for\
            \ each payment method, see Minimum amount rules. \n\nNote: Due to the\
            \ currency practices in Indonesia, when the currency is IDR, round the\
            \ amount with banker's rounding and fix the last two digits of this parameter\
            \ as 00.  \n\nMore information:\n\nValue range: 1 - unlimited\n"
      required:
      - currency
      - value
    AlipayCaptureResponse:
      type: object
      properties:
        result: *id002
        captureRequestId:
          type: string
          description: 'The unique ID that is assigned by a merchant to identify a
            capture request.


            Note: This parameter is returned when the capture status is successful.


            More information:


            Maximum length: 64 characters'
        captureId:
          type: string
          description: 'The unique ID that is assigned by Antom to identify a capture.


            Note: This parameter is returned when the capture status is successful.


            More information:


            Maximum length: 64 characters'
        paymentId:
          type: string
          description: 'The unique ID that is assigned by Antom to identify a payment.


            Note: This parameter is returned when the capture status is successful.


            More information:


            Maximum length: 64 characters'
        captureAmount: *id001
        captureTime:
          type: string
          description: "The time when Antom captures the payment. \n\nNote: This parameter\
            \ is returned when the capture status is successful.\n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
        acquirerReferenceNo:
          type: string
          description: "The unique ID assigned by the non-Antom acquirer for the transaction.\
            \  \n\nMore information:\n\nMaximum length: 64 characters"
      required:
      - result
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: "The result code that indicates the detailed processing result.\
            \  \n\nMore information:\n\nMaximum length: 64 characters"
        resultStatus:
          $ref: '#/components/schemas/ResultStatusType'
          description: 'Result status. Valid values are:


            S: Indicates that the result status is successful.

            F: Indicates that the result status is failed.

            U: Indicates that the result status is unknown. '
        resultMessage:
          type: string
          description: "Result message that explains the result code. \n\nMore information:\n\
            \nMaximum length: 256 characters"
      required:
      - resultCode
      - resultStatus
      - resultMessage
    ResultStatusType:
      type: string
      enum:
      - S
      - F
      - U
    Transit:
      type: object
      properties:
        transitType:
          $ref: '#/components/schemas/TransitType'
          description: 'Trip modes, valid values are:


            FLIGHT: indicates that the trip mode is by plane.

            TRAIN: indicates that the trip mode is by train.

            CRUISE: indicates that the trip mode is by cruise.

            COACH: indicates that the trip mode is by coach.

            '
        legs:
          type: array
          items:
            $ref: '#/components/schemas/Leg'
          maxItems: 10
          description: 'Information about sections of the trip, including departure
            time, arrival time, departure address, arrival address, transportation
            company name, carrier code and service type.


            More information:


            Maximum size: 10 elements'
        passengers:
          type: array
          items:
            $ref: '#/components/schemas/Passenger'
          description: 'Information about the passenger of the trip, including the
            passenger names, passenger email and phone number.


            More information:


            Maximum size: 100 elements'
        agentCode:
          type: string
          description: Added field for agent code
        agentName:
          type: string
          description: Added field for agent name
        ticketNumber:
          type: string
          description: Added field for ticket number
        ticketIssuerCode:
          type: string
          description: Added field for ticket issuer code
        restrictedTicketIndicator:
          type: string
          description: Added field for restricted ticket indicator
        ancillaryData:
          $ref: '#/components/schemas/AncillaryData'
          description: Ancillary data for the transit
    TransitType:
      type: string
      enum:
      - FLIGHT
      - TRAIN
      - CRUISE
      - COACH
      description: Type of transit
    Leg:
      type: object
      properties:
        departureTime:
          type: string
          description: 'Time of departure for this leg of the trip.


            More information:


            The value follows the ISO 8601 standard format. For example, "2019-11-27T12:01:01+08:00".'
        arrivalTime:
          type: string
          description: 'Time of arrival for this leg of the trip.


            More information:


            The value follows the ISO 8601 standard format. For example, "2019-11-27T12:01:01+08:00".

            '
        departureAddress:
          $ref: '#/components/schemas/Address'
          description: Hotel address.
        arrivalAddress:
          $ref: '#/components/schemas/Address'
          description: Hotel address.
        carrierName:
          type: string
          description: 'Company name of the transportation service provider for this
            leg of the trip.


            More information:


            Maximum length: 128 characters'
        carrierNo:
          type: string
          description: 'Code for the carrier for this leg of the trip.


            More information:


            Maximum length: 64 characters'
        classType:
          $ref: '#/components/schemas/ClassType'
          description: 'Service level for this leg of the trip. Valid values are:


            FIRSTLEVEL: indicates that the service is the first class. For example,
            flight first class, cruise luxury seat, train business class seat/1st
            class sleeper, coach first-level seat.

            SECONDLEVEL: indicates that the service is the second class. For example,
            fight business class, cruise business seat, train 1st class seat/2nd class
            sleeper, coach second-level seat.

            THIRDLEVEL: indicates that the service is the third class. For example,
            fight economic class or premium economic, cruise normal seat, train 2nd
            class seat/standing, coach normal seat.

            More information:


            Maximum length: 32 characters'
        departureAirportCode:
          type: string
          description: 'IATA code for the originating airport for this leg of the
            trip.


            More information:


            Maximum length: 8 characters

            '
        arrivalAirportCode:
          type: string
          description: 'IATA code for the destination airport for this leg of the
            trip.


            More information:


            Maximum length: 8 characters

            '
        fareBasis:
          type: string
          description: Fare basis code for this leg of the trip.
        couponNumber:
          type: string
          description: Coupon number associated with this leg of the trip.
        flightNumber:
          type: string
          description: Flight number for this leg of the trip.
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/payments/capture
  description: 正式环境
security: []
