---
openapi: 3.1.0
info:
  title: marketplace_createPayout
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/funds/createPayout:
    post:
      summary: createPayout
      deprecated: false
      description: 'Use this API to get the cashier page address. After getting the
        cashier page address, you can redirect the user to the cashier page to make
        a payment.

        '
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayCreatePayoutRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayCreatePayoutResponse'
          headers: {}
      security: []
components:
  schemas:
    PaymentMethod:
      type: object
      properties:
        paymentMethodType:
          type: string
          description: 'The payment method type that is included in payment method
            options. By specifying the value of this parameter, you can receive the
            cashier URL of the specified payment method returned by Alipay. See Payment
            methods to check the valid values.


            More information:


            Maximum length: 64 characters'
        paymentMethodId:
          type: string
          description: "The unique ID that is used to identify a payment method. The\
            \ value of this parameter is that of cardToken obtained from the notifyPayment\
            \ or inquiryPayment API. \n\nSpecify this parameter when the value of\
            \ paymentMethodType is CARD.\n\nMore information:\n\nMaximum length: 128\
            \ characters"
        funding:
          $ref: '#/components/schemas/FundingType'
        customerId:
          type: string
          description: 'The unique ID to identify a buyer.


            Note: Specify this field if you have the information. Providing this information
            helps to increase the accuracy of anti-money laundering and fraud detection,
            and increase payment success rates.'
        extendInfo:
          type: string
          description: 'Extended information.


            Note: Specify this field if you need to use the extended information.


            More information:


            Maximum length: 2048 characters'
        requireIssuerAuthentication:
          type: boolean
          description: 'Indicates whether Korean card transactions require authentication
            from the issuing bank. Valid values are:


            true: indicates that Korean card transactions require authentication from
            the issuing bank.

            false: indicates that Korean card transactions do not require authentication
            from the issuing bank. The same applies when you do not specify this parameter
            or the value is empty.

            Specify this parameter when all the following conditions are met:


            The value of paymentMethodType is CARD.

            The value of paymentMethodRegion is KR.

            The Korean card transactions require issuer authentication.'
        paymentMethodMetaData:
          type: object
          properties: {}
          additionalProperties:
            type: object
          description: 'Additional information required for some specific payment
            methods.  '
      required:
      - paymentMethodType
    Result:
      type: object
      properties:
        applinkUrl:
          type: string
          description: The URL for deep linking to mobile apps
        normalUrl:
          type: string
          description: The standard web URL
        schemeUrl:
          type: string
          description: The URL for custom URL schemes
        resultCode:
          type: string
          description: 'The result code.


            More information:


            Maximum length: 64 characters'
        resultStatus:
          description: "The result status. Valid values are:  \n\nS: Indicates that\
            \ the result status is successful. \nF: Indicates that the result status\
            \ is failed. \nU: Indicates that the result status is unknown. "
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: 'The result message.


            More information:


            Maximum length: 256 characters'
          maxLength: 256
      required:
      - resultCode
      - resultStatus
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: "The transaction currency, which is a 3-letter currency code\
            \ that follows the ISO 4217 standard. \n\nMore information:\n\nMaximum\
            \ length: 3 characters"
        value:
          type: string
          description: "The value of the amount as a positive integer in the smallest\
            \ currency unit. For example, if the currency is USD and the amount is\
            \ $1.00, set the value of this parameter to 100; or if the currency is\
            \ JPY and the amount is ￥1, set the value of this parameter to 1.\n\n\
            For details about the smallest currency unit, see Smallest unit of the\
            \ currency.\n\nFor details about the minimum payment amount allowed for\
            \ each payment method, see Minimum amount rules.  \n\nMore information:\n\
            \nValue range: [1, +∞)"
      required:
      - currency
      - value
    ResultStatusType:
      type:
      - string
      - 'null'
      enum:
      - S
      - F
      - U
    TransferFromDetail:
      type: object
      properties:
        transferFromMethod: &id001
          $ref: '#/components/schemas/PaymentMethod'
          description: The payment method used by the payer.
        transferFromAmount: &id002
          $ref: '#/components/schemas/Amount'
          description: 'The payout amount that the payer pays (before fee collection). '
      required:
      - transferFromMethod
      - transferFromAmount
    TransferToDetail:
      type: object
      properties:
        transferToMethod: *id001
        transferToCurrency:
          type: string
          description: "A 3-character ISO-4217 currency code representing the currency\
            \ that the beneficiary collects.  \n\nMore information:\n\nMaximum length:\
            \ 3 characters"
        feeAmount: *id002
        actualTransferToAmount: *id002
        purposeCode:
          type: string
          description: "Defines the purpose of the payout. The value of this parameter\
            \ is fixed to GSD, which means goods bought or sold.  \n\nMore information:\n\
            \nMaximum length: 3 characters"
        transferNotifyUrl:
          type: string
          description: "If you specify this parameter, Antom will send the payout\
            \ result notification to this URL. The URL must be either specified in\
            \ the request or set in Antom Dashboard.\n\nSpecify this parameter if\
            \ you want to receive an asynchronous notification of the payout result.\
            \ If this URL is specified in both the request and Antom Dashboard, the\
            \ value specified in the request takes precedence.  \n\nMore information:\n\
            \nMaximum length: 2048 characters"
        transferRemark:
          type: string
          description: 'Information provided for bank settlements.


            Specify this parameter if you want to provide additional remarks or relevant
            information regarding the payout.


            More information:


            Maximum length: 1024 characters'
      required:
      - transferToMethod
      - transferToCurrency
      - purposeCode
    AlipayCreatePayoutRequest:
      type: object
      properties:
        transferRequestId:
          type: string
          description: "The unique ID assigned by the marketplace to identify a payout\
            \ request. \n\nMore information:\n\nThis field is an API idempotency field.For\
            \ requests that are initiated with the same value of transferRequestId\
            \ and reach a final status (S or F), the same result is to be returned\
            \ for the request.\nMaximum length: 64 characters"
        transferFromDetail: &id003
          $ref: '#/components/schemas/TransferFromDetail'
          description: 'Details of the payout payer.  '
        transferToDetail: &id004
          $ref: '#/components/schemas/TransferToDetail'
          description: 'Details of the payout beneficiary. '
      required:
      - transferRequestId
      - transferFromDetail
      - transferToDetail
    AlipayCreatePayoutResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
          description: 'Indicates whether this API is called successfully. '
        transferId:
          type: string
          description: "The unique ID assigned by Antom to identify a payout.\n\n\
            This parameter is returned when the value of result.resultStatus is U.\
            \ \n\nMore information:\n\nMaximum length: 64 characters"
        transferRequestId:
          type: string
          description: "The unique ID assigned by the marketplace to identify a payout\
            \ request.\n\nThis parameter is returned when the value of result.resultStatus\
            \ is U. \n\nMore information:\n\nMaximum length: 64 characters"
        transferFromDetail: *id003
        transferToDetail: *id004
      required:
      - result
    FundingType:
      type: string
      enum:
      - CREDIT
      - DEBIT
      - PREPAID
      - CHARGE
      - DEFERRED_DEBIT
      description: The funding source type for the payment method
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/funds/createPayout
  description: 正式环境
security: []
