---
openapi: 3.1.0
info:
  title: customs_declare
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/customs/declare:
    post:
      summary: declare
      deprecated: false
      description: 'Use this API to get the cashier page address. After getting the
        cashier page address, you can redirect the user to the cashier page to make
        a payment.

        '
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayCustomsDeclareRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayCustomsDeclareResponse'
          headers: {}
      security: []
components:
  schemas:
    Result:
      type: object
      properties:
        actualRefundAmount:
          $ref: '#/components/schemas/Amount'
        resultCode:
          type: string
          description: 'The result code.


            More information:


            Maximum length: 64 characters'
        resultStatus:
          description: "The result status. Valid values are:  \n\nS: Indicates that\
            \ the result status is successful. \nF: Indicates that the result status\
            \ is failed. \nU: Indicates that the result status is unknown. "
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: 'The result message.


            More information:


            Maximum length: 256 characters'
          maxLength: 256
      required:
      - resultCode
      - resultStatus
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: "The transaction currency, which is a 3-letter currency code\
            \ that follows the ISO 4217 standard. \n\nMore information:\n\nMaximum\
            \ length: 3 characters"
        value:
          type: string
          description: "The value of the amount as a positive integer in the smallest\
            \ currency unit. For example, if the currency is USD and the amount is\
            \ $1.00, set the value of this parameter to 100; or if the currency is\
            \ JPY and the amount is ￥1, set the value of this parameter to 1.\n\n\
            For details about the smallest currency unit, see Smallest unit of the\
            \ currency.\n\nFor details about the minimum payment amount allowed for\
            \ each payment method, see Minimum amount rules.  \n\nMore information:\n\
            \nValue range: [1, +∞)"
      required:
      - currency
      - value
    ResultStatusType:
      type:
      - string
      - 'null'
      enum:
      - S
      - F
      - U
    UserName:
      type: object
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        fullName:
          type: string
    CertificateType:
      type: string
      enum:
      - ENTERPRISE_REGISTRATION
      - LICENSE_INFO
      - ID_CARD
      - PASSPORT
      - DRIVING_LICENSE
      - CPF
      - CNPJ
    Certificate:
      type: object
      properties:
        certificateType:
          $ref: '#/components/schemas/CertificateType'
          description: 'Identification type of the buyer. Valid values are:


            ID_CARD: indicates that the identification type is an identification card.
            When customs.region is CN, use this value.

            PASSPORT: indicates that the identification type is a passport.'
        certificateNo:
          type: string
          description: 'Identification number of the buyer.


            More information:


            Maximum length: 64 characters'
        holderName:
          $ref: '#/components/schemas/UserName'
          description: 'The buyer name.


            Note: Specify this field when CertificateType is ID_CARD. '
        fileKeys:
          type: array
          items:
            type: string
        certificateAuthority:
          type: string
      required:
      - certificateType
      - certificateNo
    AlipayCustomsDeclareRequest:
      type: object
      properties:
        declarationRequestId:
          type: string
          description: "The unique ID that is assigned by the merchant to identify\
            \ a declaration request. The length of each declaration request number\
            \ ranges from 1 to 32 bits.  \n\nMore information:\n\nThis field is an\
            \ API idempotency field.\nMaximum length: 32 characters"
        paymentId:
          type: string
          description: 'The unique ID that is assigned by Antom to identify a payment.


            More information:


            Maximum length: 64 characters'
        declarationAmount:
          $ref: '#/components/schemas/Amount'
          description: "The accumulated transaction declaration amount, which cannot\
            \ be greater than the total transaction amount. Only China customs declaration\
            \ is supported. The default currency is CNY (Chinese Renminbi).  \n\n\
            Note: This field can be obtained from the customsDeclarationAmount field\
            \ in the notifyPayment request and inquiryPayment response."
        customs:
          $ref: '#/components/schemas/CustomsInfo'
          description: The customs information
        merchantCustomsInfo:
          $ref: '#/components/schemas/MerchantCustomsInfo'
          description: 'The merchant information that is registered in the customs
            system. '
        splitOrder:
          type: boolean
          description: 'The merchant can decide whether the order is split for declaration.
            If the value of this field is true, order splitting is allowed. If the
            value of this field is false, no order splitting is allowed.


            '
        subOrderId:
          type: string
          description: "The suborder ID that is assigned by the merchant.\n\nNotes:\
            \ \n\nSpecify this field when splitOrder is true. The suborder ID is transmitted\
            \ to the customs as the order ID in the payment information when the following\
            \ business scenarios occur:\nA payment contains multiple commodities and\
            \ needs to be submitted to different customs, or the customs require separate\
            \ submission according to the commodities.\nIn a combined payment, a customs\
            \ declaration is required for some commodities. \nOther situations where\
            \ customs declaration needs to be split. \nAfter the order is split, ensure\
            \ that the suborder ID of these two suborders is the same as the order\
            \ ID in the payment information. Otherwise, the order will be rejected\
            \ due to information inconsistency. \nMore information:\n\nMaximum length:\
            \ 64 characters\n"
        buyerCertificate:
          $ref: '#/components/schemas/Certificate'
          description: "The buyer information.\n\nNotes: \n\nSpecify this field when\
            \ the buyer information needs to be verified. Actually, it is recommended\
            \ to provide the buyer information in this API to meet the customs declaration\
            \ policy requirements and facilitate Antom to check the buyer information.\
            \ Although this field is optional, it is suggested to specify this field\
            \ because customs will check buyer information at random. \nIf this field\
            \ is not specified, the merchant needs to ensure that the buyer and payer\
            \ information is consistent. Any inconsistency detected by customs will\
            \ result in a rejected declaration. Specifying this field will reduce\
            \ the risk of the order being returned. "
      required:
      - declarationRequestId
      - paymentId
      - declarationAmount
      - customs
      - merchantCustomsInfo
      - splitOrder
    CustomsInfo:
      type: object
      properties:
        customsCode:
          type: string
          description: "The customs code. See the Customs Code section on this page\
            \ for details. \n\nMore information:\n\nMaximum length: 28 characters"
        region:
          type: string
          description: "The customs region, which follows the 2-character ISO 3166\
            \ country/region code. \n\nNote: Only the China customs region of CN is\
            \ supported for now. \n\nMore information:\n\nMaximum length: 2 characters"
      required:
      - customsCode
      - region
    MerchantCustomsInfo:
      type: object
      properties:
        merchantCustomsCode:
          type: string
          description: "The merchant recordation number in the customs system. \n\n\
            More information:\n\nMaximum length: 128 characters"
        merchantCustomsName:
          type: string
          description: "The merchant recordation name in the customs system. \n\n\
            More information:\n\nMaximum length: 256 characters"
      required:
      - merchantCustomsCode
      - merchantCustomsName
    AlipayCustomsDeclareResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
          description: "The request result, which contains information such as status\
            \ and error codes. \n\nNote: This field does not indicate the declaration\
            \ result. This field only indicates whether the declare API is called\
            \ successfully. "
        customsPaymentId:
          type: string
          description: "The payment ID provided to the customs by the declaration\
            \ service provider.\n\nNote: This field is returned when result.resultCode\
            \ is S. \n\nMore information:\n\nMaximum length: 64 characters"
        customsOrderId:
          type: string
          description: "The order ID provided to the customs by the declaration service\
            \ provider.\n\nNote: This field is returned when result.resultCode is\
            \ S. \n\nMore information:\n\nMaximum length: 64 characters"
        identityCheckResult:
          $ref: '#/components/schemas/IdentityCheckResult'
          description: 'The identity check result. Valid values are:


            CHECK_PASSED: indicates that the buyer is also the payer.

            CHECK_NOT_PASSED: indicates that the buyer is not the payer.

            Note: This field is returned when result.resultCode is S. If this field
            is not returned, it indicates that the buyer''s identity is not checked. '
        clearingChannel:
          $ref: '#/components/schemas/ClearingChannel'
          description: "The clearing organization. Valid values are:\n\nCUP: indicates\
            \ that the clearing channel is Unionpay. For example, when the user uses\
            \ the bank card to pay, this value might be returned.\nNUCC: indicates\
            \ that the clearing channel is NetsUnion. For example, when the user uses\
            \ the bank card to pay, this value might be returned.\nOTHER: indicates\
            \ that the clearing channel is others. For example, when the user uses\
            \ credit products such as Huabei, this value is returned.\nNote: This\
            \ field is returned when these two conditions are met:\n\nresultCode is\
            \ S. \nThe customs receipt is returned. "
        clearingTransactionId:
          type: string
          description: "The clearing organization's serial number.\n\nNote: This field\
            \ is returned when these two conditions are met:\n\nresultCode is S.\n\
            The customs receipt is returned. \nMore information:\n\nMaximum length:\
            \ 64 characters"
        customsProviderRegistrationId:
          type: string
          description: "The registration ID in the customs system.\n\nNote: This field\
            \ is returned when these two conditions are met:\n\nresultCode is S. \n\
            The customs receipt is returned.  \nMore information:\n\nMaximum length:\
            \ 32 characters"
      required:
      - result
    IdentityCheckResult:
      type: string
      enum:
      - CHECK_PASSED
      - CHECK_NOT_PASSED
    ClearingChannel:
      type: string
      enum:
      - CUP
      - NUCC
      - OTHER
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/customs/declare
  description: 正式环境
security: []
