components:
  schemas:
    AcquirerInfo:
      properties:
        acquirerMerchantId:
          type: string
        acquirerName:
          type: string
        acquirerResultCode:
          type: string
        acquirerResultMessage:
          type: string
        acquirerTransactionId:
          type: string
        referenceRequestId:
          type: string
      type: object
    AlipayInquiryRefundRequest:
      properties:
        merchantAccountId:
          type: string
        refundId:
          description: 'The unique ID assigned by Antom to identify a refund. refundRequestId
            and refundId cannot both be null. A one-to-one correspondence between
            refundId and refundRequestId exists. If both refundRequestId and refundId
            are specified, refundId takes precedence.


            More information:


            Maximum length: 64 characters'
          type: string
        refundRequestId:
          description: 'The unique ID assigned by a merchant to identify a refund
            request. refundRequestId and refundId cannot both be null. Special characters
            are not supported. If both refundRequestId and refundId are specified,
            refundId takes precedence.


            More information:


            Maximum length: 64 characters'
          type: string
      type: object
    AlipayInquiryRefundResponse:
      properties:
        acquirerInfo:
          $ref: '#/components/schemas/AcquirerInfo'
        arn:
          description: Alipay Reference Number
          example: '122445'
          type: string
        grossSettlementAmount:
          $ref: '#/components/schemas/Amount'
          description: 'The refund amount that is initiated by the merchant.


            Note: This field is null when the refund record cannot be found, or result.resultStatus
            is F or U. '
        refundAmount:
          $ref: '#/components/schemas/Amount'
          description: 'The refund amount that is initiated by the merchant.


            Note: This field is null when the refund record cannot be found, or result.resultStatus
            is F or U. '
        refundId:
          description: 'The unique ID assigned by Antom to identify a refund. A one-to-one
            correspondence between refundId and refundRequestId exists.


            Note: This field is null when the refund record cannot be found, or result.resultStatus
            is F or U. '
          type: string
        refundRequestId:
          description: "The unique ID assigned by the merchant to identify a refund\
            \ request.\n\nNote: This field is null when the refund record cannot be\
            \ found, or result.resultStatus is F or U. \n\nMore information:\n\nMaximum\
            \ length: 64 characters"
          type: string
        refundStatus:
          $ref: '#/components/schemas/TransactionStatusType'
          description: "Indicates the final status of the Antom refund, not the Alipay+\
            \ Mobile Payment Provider (Alipay+ payment methods) side. Valid values\
            \ are:  \n\nSUCCESS: Indicates the refund is successful. \nPROCESSING:\
            \ Indicates the refund is still under process. \nFAIL: Indicates the refund\
            \ failed.\nNote: This field is null when the refund record cannot be found,\
            \ or result.resultStatus is F or U. \n\nMore information:\n\nMaximum length:\
            \ 16 characters\n"
        refundTime:
          description: "The date and time when the refund reaches a final state of\
            \ success on the Antom side, not the Alipay+ Mobile Payment Provider (Alipay+\
            \ payment methods) side. \n\nNote: This field is returned when the value\
            \ of refundStatus is SUCCESS.\n\nMore information:\n\nThe value follows\
            \ the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
          type: string
        result:
          $ref: '#/components/schemas/Result'
          description: 'The request result contains information such as status and
            error codes.


            Note: This field does not indicate the refund result. This field only
            indicates whether the inquiryRefund interface is called successfully. '
        settlementQuote:
          $ref: '#/components/schemas/Quote'
          description: 'The exchange rate between the settlement currency and payment
            currency.


            Note: This field is returned when grossSettlementAmount is returned.'
      required:
      - result
      type: object
    Amount:
      properties:
        currency:
          description: "The 3-letter currency code that follows the ISO 4217 standard.\
            \ \n\nMore information:\n\nMaximum length: 3 characters"
          type: string
        value:
          description: 'The amount to charge as a positive integer in the smallest
            currency unit. For example, $1.00 should be charged as 100 cents to charge
            USD 1.00, or 100 to charge JPY 100, a 0-decimal currency.


            Note: For more information about the smallest currency unit, see Currency
            codes for details.


            More information:


            Value range: 1 - unlimited'
          type: string
      required:
      - currency
      - value
      type: object
    Quote:
      properties:
        guaranteed:
          description: Guaranteed exchange rate available for payment.
          type: boolean
        quoteCurrencyPair:
          description: 'The exchange rate between settlement currency and transaction
            currency. Two currencies are separated with a slash and use the 3-letter
            ISO-4217 currency code.


            More information:


            Maximum length: 16 characters'
          type: string
        quoteExpiryTime:
          description: "The expiration time of the exchange rate. \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
          type: string
        quoteId:
          description: 'The unique ID that is assigned by Antom to identify an exchange
            rate.


            More information:


            Maximum length: 64 characters'
          type: string
        quotePrice:
          description: 'The exchange rate used when a currency conversion between
            settlement currency and transaction currency occurs.


            More information:


            Value range: 1 - unlimited'
          type: number
        quoteStartTime:
          description: "The effective time of the exchange rate. \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
          type: string
      required:
      - quoteCurrencyPair
      - quotePrice
      type: object
    Result:
      properties:
        resultCode:
          description: 'Result code


            More information:


            Maximum length: 64 characters'
          type: string
        resultMessage:
          description: 'Result message


            More information:


            Maximum length: 256 characters

            '
          type: string
        resultStatus:
          $ref: '#/components/schemas/ResultStatusType'
          description: "Result status. Valid values are:  \n\nS: Indicates that the\
            \ result status is successful. \nF: Indicates that the result status is\
            \ failed. \nU: Indicates that the result status is unknown. \nMore information:\n\
            \nMaximum length: 1 character"
      required:
      - resultCode
      - resultStatus
      - resultMessage
      type: object
    ResultStatusType:
      enum:
      - S
      - F
      - U
      type: string
    TransactionStatusType:
      enum:
      - SUCCESS
      - FAIL
      - PROCESSING
      - CANCELLED
      - PENDING
      type: string
  securitySchemes: {}
info:
  description: ''
  title: payments_inquiryRefund
  version: 1.0.0
openapi: 3.1.0
paths:
  /ams/api/v1/payments/inquiryRefund:
    post:
      deprecated: false
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                merchantAccountId:
                  type: string
                refundId:
                  description: 'The unique ID assigned by Antom to identify a refund.
                    refundRequestId and refundId cannot both be null. A one-to-one
                    correspondence between refundId and refundRequestId exists. If
                    both refundRequestId and refundId are specified, refundId takes
                    precedence.


                    More information:


                    Maximum length: 64 characters'
                  type: string
                refundRequestId:
                  description: 'The unique ID assigned by a merchant to identify a
                    refund request. refundRequestId and refundId cannot both be null.
                    Special characters are not supported. If both refundRequestId
                    and refundId are specified, refundId takes precedence.


                    More information:


                    Maximum length: 64 characters'
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  acquirerInfo:
                    $ref: '#/components/schemas/AcquirerInfo'
                  grossSettlementAmount:
                    $ref: '#/components/schemas/Amount'
                    description: 'The refund amount that is initiated by the merchant.


                      Note: This field is null when the refund record cannot be found,
                      or result.resultStatus is F or U. '
                  refundAmount:
                    $ref: '#/components/schemas/Amount'
                    description: 'The refund amount that is initiated by the merchant.


                      Note: This field is null when the refund record cannot be found,
                      or result.resultStatus is F or U. '
                  refundId:
                    description: 'The unique ID assigned by Antom to identify a refund.
                      A one-to-one correspondence between refundId and refundRequestId
                      exists.


                      Note: This field is null when the refund record cannot be found,
                      or result.resultStatus is F or U. '
                    type: string
                  refundRequestId:
                    description: "The unique ID assigned by the merchant to identify\
                      \ a refund request.\n\nNote: This field is null when the refund\
                      \ record cannot be found, or result.resultStatus is F or U.\
                      \ \n\nMore information:\n\nMaximum length: 64 characters"
                    type: string
                  refundStatus:
                    $ref: '#/components/schemas/TransactionStatusType'
                    description: "Indicates the final status of the Antom refund,\
                      \ not the Alipay+ Mobile Payment Provider (Alipay+ payment methods)\
                      \ side. Valid values are:  \n\nSUCCESS: Indicates the refund\
                      \ is successful. \nPROCESSING: Indicates the refund is still\
                      \ under process. \nFAIL: Indicates the refund failed.\nNote:\
                      \ This field is null when the refund record cannot be found,\
                      \ or result.resultStatus is F or U. \n\nMore information:\n\n\
                      Maximum length: 16 characters\n"
                  refundTime:
                    description: "The date and time when the refund reaches a final\
                      \ state of success on the Antom side, not the Alipay+ Mobile\
                      \ Payment Provider (Alipay+ payment methods) side. \n\nNote:\
                      \ This field is returned when the value of refundStatus is SUCCESS.\n\
                      \nMore information:\n\nThe value follows the ISO 8601 standard\
                      \ format. For example, \"2019-11-27T12:01:01+08:00\"."
                    type: string
                  result:
                    $ref: '#/components/schemas/Result'
                    description: 'The request result contains information such as
                      status and error codes.


                      Note: This field does not indicate the refund result. This field
                      only indicates whether the inquiryRefund interface is called
                      successfully. '
                  settlementQuote:
                    $ref: '#/components/schemas/Quote'
                    description: 'The exchange rate between the settlement currency
                      and payment currency.


                      Note: This field is returned when grossSettlementAmount is returned.'
                required:
                - result
                type: object
          description: ''
          headers: {}
      security: []
      summary: inquiryRefund
      tags: []
security: []
servers:
- description: 正式环境
  url: https://open-sea-global.alipay.com/ams/api/v1/payments/inquiryRefund
tags: []
