---
openapi: 3.1.0
info:
  title: InquireExchangeRate
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/payments/inquireExchangeRate:
    get:
      summary: inquireExchangeRate
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayInquireExchangeRateRequest'
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayInquireExchangeRateResponse'
          headers: {}
      security: []
webhooks: {}
components:
  schemas:
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: "The result status. Valid values are:\n\nS: indicates that\
            \ the result status is successful.\nF: indicates that the result status\
            \ is failed. \nU: indicates that the result status is unknown. "
          type: object
          properties: {}
        resultMessage:
          type: string
          description: The result message.
      required:
      - resultCode
      - resultStatus
    Quote:
      type: object
      properties:
        quoteId:
          type: string
          description: "The unique ID that is assigned by Antom to identify an exchange\
            \ rate. \n\nMore information:\n\nMaximum length: 64 characters"
        quoteCurrencyPair:
          type: string
          description: "The exchange rate between settlement currency and transaction\
            \ currency. Two currencies are separated with a slash and use the three-letter\
            \ ISO-4217 currency code.  \n\nMore information:\n\nMaximum length: 16\
            \ characters"
        quotePrice:
          type: number
          description: "The exchange rate used when a currency conversion between\
            \ settlement currency and transaction currency occurs.  \n\nMore information:\n\
            \nValue range: 1 - unlimited"
        quoteStartTime:
          type: string
          description: "Effective time of the exchange rate. \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            .\n"
        quoteExpiryTime:
          type: string
          description: "Expiration time of the exchange rate.  \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            .\n"
        guaranteed:
          type: boolean
          description: "Guaranteed exchange rate available for payment.  \n\n"
        exchangeAmount:
          $ref: '#/components/schemas/Amount'
          description: Added field for exchange amount
      required:
      - quoteCurrencyPair
      - quotePrice
    ProductCodeType:
      type: string
      enum:
      - CASHIER_PAYMENT
      - AGREEMENT_PAYMENT
      - IN_STORE_PAYMENT
    CurrencyPair:
      type: object
      properties:
        sellCurrency:
          type: string
        buyCurrency:
          type: string
    AlipayInquireExchangeRateResponse:
      type: object
      properties:
        quotes:
          type: array
          items:
            $ref: '#/components/schemas/Quote'
        result:
          $ref: '#/components/schemas/Result'
      required:
      - quotes
      - result
    AlipayInquireExchangeRateRequest:
      type: object
      properties:
        merchantAccountId:
          type: string
        paymentCurrency:
          type: string
        currencyPairs:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyPair'
        sellCurrency:
          type: string
        buyCurrency:
          type: string
        productCode:
          $ref: '#/components/schemas/ProductCodeType'
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/payments/inquireExchangeRate
