---
openapi: 3.1.0
info:
  title: aba-inquireCardDetail
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/aba/cards/inquireCardDetail:
    post:
      summary: inquireCardDetail
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayInquireCardDetailRequest'
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayInquireCardDetailResponse'
          headers: {}
      security: []
webhooks: {}
components:
  schemas:
    AlipayInquireCardDetailRequest:
      type: object
      properties:
        assetId:
          type: string
          description: 卡资产ID。
      required:
      - assetId
    ResultStatusType:
      type: string
      enum:
      - S
      - F
      - U
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: "The result status. Valid values are:\n\nS: indicates that\
            \ the result status is successful.\nF: indicates that the result status\
            \ is failed. \nU: indicates that the result status is unknown. "
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: The result message.
      required:
      - resultCode
      - resultStatus
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: "The 3-letter currency code that follows the ISO 4217 standard.\
            \ \n\nMore information:\n\nMaximum length: 3 characters"
        value:
          type: string
          description: "The value of the amount as a positive integer in the smallest\
            \ currency unit. For example, if the currency is USD and the amount is\
            \ $1.00, set the value of this parameter to 100; or if the currency is\
            \ JPY and the amount is ￥1, set the value of this parameter to 1.  \n\n\
            For details about the smallest currency unit, see Smallest unit of the\
            \ currency .\n\nFor details about the minimum payment amount allowed for\
            \ each payment method, see Minimum amount rules. \n\nNote: Due to the\
            \ currency practices in Indonesia, when the currency is IDR, round the\
            \ amount with banker's rounding and fix the last two digits of this parameter\
            \ as 00.  \n\nMore information:\n\nValue range: 0 - unlimited\n"
      required:
      - currency
      - value
    Address:
      type: object
      properties:
        region:
          type: string
          description: "The 2-letter country or region code. For more information,\
            \ see the ISO 3166 Country Codes standard. \n\nMore information:\n\nMaximum\
            \ length: 2 characters"
        state:
          type: string
          description: "The state, country, or province name. \n\nFor card payments,\
            \ if your business entity is in the United States, and the card issuing\
            \ country is Canada, the United States, or the United Kingdom, set the\
            \ value to a region code that consists of two to three characters and\
            \ follows the ISO 3166-2 standard. \n\nMore information:\n\nMaximum length:\
            \ 8 characters"
        city:
          type: string
          description: "The city, district, suburb, town, or village name. \n\nMore\
            \ information:\n\nMaximum length: 32 characters\n"
        address1:
          type: string
          description: "Address line 1, for example, the street address, PO box, and\
            \ company name. \n\nMore information:\n\nMaximum length: 256 characters"
        address2:
          type: string
          description: "Address line 2, for example, the apartment, suite, unit, and\
            \ building information. \n\nMore information:\n\nMaximum length: 256 characters"
        zipCode:
          type: string
          description: "The ZIP or postal code. \n\nFor card payments, if your business\
            \ entity is in the United States, specify this parameter according to\
            \ the following parameter value requirements:\n\nOnly contains numbers,\
            \ letters, hyphens, and spaces.\nMust be within ten characters. \nMore\
            \ information:\n\nMaximum length: 32 characters"
        label:
          type: string
        address3:
          type: string
      required:
      - region
    UserName:
      type: object
      properties:
        firstName:
          type: string
          description: 'First name.


            More information:


            Maximum length: 32 characters'
        middleName:
          type: string
          description: 'Middle name


            More information:


            Maximum length: 32 characters'
        lastName:
          type: string
          description: 'Last name


            More information:


            Maximum length: 32 characters'
        fullName:
          type: string
          description: 'Full name


            More information:


            Maximum length: 128 characters'
    AuthorizationControl:
      type: object
      properties:
        cardActiveTime:
          type: string
          description: 'If not present, It will be activated when the card is created.
            Datetime UTC time: 2018-10-31T00:00:00+0800 ISO 8601'
        cardCancelTime:
          type: string
          description: 'Datetime UTC time: 2018-10-31T00:00:00+0800 ISO 8601'
        allowedMerchantCategoryList:
          type: array
          items:
            type: string
          maxItems: 570
          description: Allowed MCC (Merchant Category Code) list. If not set or left
            empty, all transactions are allowed.
        allowedAuthTimes:
          type: integer
          minimum: 0
          description: Indicates the number of allowed authorization times. If not
            set or left empty, all transactions are allowed.
        allowedCurrencies:
          type: array
          items:
            type: string
            pattern: ^[A-Z]{3}$
          maxItems: 200
          description: Allowed transaction currencies (ISO 4217 three-letter codes).
            If not set, no currency restriction applies.
        cardLimitDetail:
          $ref: '#/components/schemas/CardLimitDetail'
      required:
      - cardLimitDetail
    Limit:
      type: object
      properties:
        remainingLimit: &id001
          description: '剩余额度。

            Remaining available limit.'
          $ref: '#/components/schemas/Amount'
        rangeLimit: *id001
        usedLimit: *id001
      required:
      - remainingLimit
      - rangeLimit
      - usedLimit
    CardLimitDetail:
      type: object
      properties:
        perTransactionLimit: *id001
        dailyLimit: &id002
          description: '日最大限额。

            Daily spending maximum limit.'
          $ref: '#/components/schemas/Limit'
        monthlyLimit: *id002
        perCardLimit: *id002
        dailyLimitMax:
          type: string
        monthlyLimitMax:
          type: string
        perTransactionLimitMax:
          type: string
        perCardLimitMax:
          type: string
      required:
      - perTransactionLimit
      - dailyLimit
      - monthlyLimit
    CardholderInfo:
      type: object
      properties:
        cardHolderName:
          description: The name of the card holder.
          $ref: '#/components/schemas/UserName'
        billAddress:
          description: The billing address.
          $ref: '#/components/schemas/Address'
      required:
      - cardHolderName
      - billAddress
      $defs:
        CardholderName:
          type: object
          properties:
            firstName:
              type: string
              description: The first name of the card holder.
            lastName:
              type: string
              description: The last name of the card holder.
          required:
          - firstName
          - lastName
        Address:
          type: object
          properties:
            city:
              type: string
              description: City
            region:
              type: string
              maxLength: 2
              description: Region (e.g., state code or ISO region)
            zipCode:
              type: string
              description: ZIP or postal code
            state:
              type: string
              description: State, province, or country subdivision
            address1:
              type: string
              maxLength: 100
              description: Address line 1, such as the building name, room number
                and business name.
            address2:
              type: string
              maxLength: 100
              description: Address line 2, such as the apartment or unit number.
            address3:
              type: string
              maxLength: 100
              description: Address line 3, such as the street name.
          required:
          - city
          - region
          - zipCode
          - state
          - address1
    AlipayInquireCardDetailResponse:
      type: object
      properties:
        result:
          description: Represents the result of the interface call
          $ref: '#/components/schemas/Result'
        assetId:
          type: string
          maxLength: 32
          description: '卡资产ID。

            Card asset Id.'
        cardNickName:
          type: string
          maxLength: 120
          description: '由用户定义的卡昵称，可以帮助用户更方便地管理多张卡。

            User-defined card nickname, designed to help users manage multiple cards
            more conveniently.'
        cardStatus:
          type: string
          maxLength: 32
          enum:
          - ACTIVE
          - FROZEN
          - CANCEL
          description: "卡状态。可取值范围：\nACTIVE：可正常使用\nFROZEN：已冻结\nCANCEL：已注销\n\nCard Status:\
            \ Represents the current state of the card. Possible values include: \
            \ \nACTIVE: The card is active and can be used normally.  \nFROZEN: The\
            \ card has been frozen and cannot be used temporarily.  \nCANCEL: The\
            \ card has been canceled and is no longer valid."
        maskedCardNo:
          type: string
          maxLength: 32
          description: '脱敏卡号。

            Masked card number.'
        cardBrand:
          type: string
          maxLength: 32
          enum:
          - MASTERCARD
          description: "卡品牌。\n可取值范围：\nMASTERCARD\n\nCard Brand: Indicates the brand\
            \ or network of the card. Possible value:  \nMASTERCARD: The card is part\
            \ of the Mastercard network."
        createdTime:
          type: string
          description: 'Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601'
          maxLength: 16
        updatedTime:
          type: string
          description: 'Datetime UTC time: 2018-10-31T00:00:00+0800. ISO 8601'
          maxLength: 16
        purpose:
          type: string
          maxLength: 512
          description: Purpose of the card
        note:
          type: string
          maxLength: 512
          description: Note information of card application
        metadata:
          type: object
          additionalProperties:
            type: string
            maxLength: 128
          maxProperties: 30
          propertyNames:
            maxLength: 32
          description: 'Customer metadata in key-value format.

            - Key max length: 32

            - Value max length: 128

            - Max number of keys: 30

            - Total JSON string max length: 3096'
          properties: {}
        authorizationControl:
          $ref: '#/components/schemas/AuthorizationControl'
        cardholderinfo:
          $ref: '#/components/schemas/CardholderInfo'
      required:
      - result
      - assetId
      - cardStatus
      - maskedCardNo
      - cardBrand
      - createdTime
      - updatedTime
      - purpose
      - authorizationControl
      - cardholderinfo
    authorizationControl:
      type: object
      properties:
        CardLimitInfo:
          $ref: '#/components/schemas/CardLimitInfo'
    CardLimitInfo:
      type: object
      properties:
        currency:
          type: string
        dailyLimitMax:
          type: string
        monthlyLimitMax:
          type: string
        perTransactionLimitMax:
          type: string
        perCardLimitMax:
          type: string
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/aba/cards/inquireCardDetail
