---
openapi: 3.1.0
info:
  title: payments_inquiryRefund
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/payments/inquiryRefund:
    post:
      summary: inquiryRefund
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refundRequestId:
                  type: string
                  description: 'The unique ID assigned by a merchant to identify a
                    refund request. refundRequestId and refundId cannot both be null.
                    Special characters are not supported. If both refundRequestId
                    and refundId are specified, refundId takes precedence.


                    More information:


                    Maximum length: 64 characters'
                refundId:
                  type: string
                  description: 'The unique ID assigned by Antom to identify a refund.
                    refundRequestId and refundId cannot both be null. A one-to-one
                    correspondence between refundId and refundRequestId exists. If
                    both refundRequestId and refundId are specified, refundId takes
                    precedence.


                    More information:


                    Maximum length: 64 characters'
                merchantAccountId:
                  type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: &id002
                    $ref: '#/components/schemas/Result'
                    description: 'The request result contains information such as
                      status and error codes.


                      Note: This field does not indicate the refund result. This field
                      only indicates whether the inquiryRefund interface is called
                      successfully. '
                  refundId:
                    type: string
                    description: 'The unique ID assigned by Antom to identify a refund.
                      A one-to-one correspondence between refundId and refundRequestId
                      exists.


                      Note: This field is null when the refund record cannot be found,
                      or result.resultStatus is F or U. '
                  refundRequestId:
                    type: string
                    description: "The unique ID assigned by the merchant to identify\
                      \ a refund request.\n\nNote: This field is null when the refund\
                      \ record cannot be found, or result.resultStatus is F or U.\
                      \ \n\nMore information:\n\nMaximum length: 64 characters"
                  refundAmount: &id001
                    $ref: '#/components/schemas/Amount'
                    description: 'The refund amount that is initiated by the merchant.


                      Note: This field is null when the refund record cannot be found,
                      or result.resultStatus is F or U. '
                  refundStatus: &id003
                    $ref: '#/components/schemas/TransactionStatusType'
                    description: "Indicates the final status of the Antom refund,\
                      \ not the Alipay+ Mobile Payment Provider (Alipay+ payment methods)\
                      \ side. Valid values are:  \n\nSUCCESS: Indicates the refund\
                      \ is successful. \nPROCESSING: Indicates the refund is still\
                      \ under process. \nFAIL: Indicates the refund failed.\nNote:\
                      \ This field is null when the refund record cannot be found,\
                      \ or result.resultStatus is F or U. \n\nMore information:\n\n\
                      Maximum length: 16 characters\n"
                  refundTime:
                    type: string
                    description: "The date and time when the refund reaches a final\
                      \ state of success on the Antom side, not the Alipay+ Mobile\
                      \ Payment Provider (Alipay+ payment methods) side. \n\nNote:\
                      \ This field is returned when the value of refundStatus is SUCCESS.\n\
                      \nMore information:\n\nThe value follows the ISO 8601 standard\
                      \ format. For example, \"2019-11-27T12:01:01+08:00\"."
                  grossSettlementAmount: *id001
                  settlementQuote: &id004
                    $ref: '#/components/schemas/Quote'
                    description: 'The exchange rate between the settlement currency
                      and payment currency.


                      Note: This field is returned when grossSettlementAmount is returned.'
                  acquirerInfo: &id005
                    $ref: '#/components/schemas/AcquirerInfo'
                required:
                - result
          headers: {}
      security: []
components:
  schemas:
    AlipayInquiryRefundRequest:
      type: object
      properties:
        refundRequestId:
          type: string
          description: 'The unique ID assigned by a merchant to identify a refund
            request. refundRequestId and refundId cannot both be null. Special characters
            are not supported. If both refundRequestId and refundId are specified,
            refundId takes precedence.


            More information:


            Maximum length: 64 characters'
        refundId:
          type: string
          description: 'The unique ID assigned by Antom to identify a refund. refundRequestId
            and refundId cannot both be null. A one-to-one correspondence between
            refundId and refundRequestId exists. If both refundRequestId and refundId
            are specified, refundId takes precedence.


            More information:


            Maximum length: 64 characters'
        merchantAccountId:
          type: string
    AlipayInquiryRefundResponse:
      type: object
      properties:
        result: *id002
        refundId:
          type: string
          description: 'The unique ID assigned by Antom to identify a refund. A one-to-one
            correspondence between refundId and refundRequestId exists.


            Note: This field is null when the refund record cannot be found, or result.resultStatus
            is F or U. '
        refundRequestId:
          type: string
          description: "The unique ID assigned by the merchant to identify a refund\
            \ request.\n\nNote: This field is null when the refund record cannot be\
            \ found, or result.resultStatus is F or U. \n\nMore information:\n\nMaximum\
            \ length: 64 characters"
        refundAmount: *id001
        refundStatus: *id003
        refundTime:
          type: string
          description: "The date and time when the refund reaches a final state of\
            \ success on the Antom side, not the Alipay+ Mobile Payment Provider (Alipay+\
            \ payment methods) side. \n\nNote: This field is returned when the value\
            \ of refundStatus is SUCCESS.\n\nMore information:\n\nThe value follows\
            \ the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
        grossSettlementAmount: *id001
        settlementQuote: *id004
        acquirerInfo: *id005
      required:
      - result
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: "The 3-letter currency code that follows the ISO 4217 standard.\
            \ \n\nMore information:\n\nMaximum length: 3 characters"
        value:
          type: string
          description: 'The amount to charge as a positive integer in the smallest
            currency unit. For example, $1.00 should be charged as 100 cents to charge
            USD 1.00, or 100 to charge JPY 100, a 0-decimal currency.


            Note: For more information about the smallest currency unit, see Currency
            codes for details.


            More information:


            Value range: 1 - unlimited'
      required:
      - currency
      - value
    TransactionStatusType:
      type: string
      enum:
      - SUCCESS
      - FAIL
      - PROCESSING
      - CANCELLED
      - PENDING
    Quote:
      type: object
      properties:
        quoteId:
          type: string
          description: 'The unique ID that is assigned by Antom to identify an exchange
            rate.


            More information:


            Maximum length: 64 characters'
        quoteCurrencyPair:
          type: string
          description: 'The exchange rate between settlement currency and transaction
            currency. Two currencies are separated with a slash and use the 3-letter
            ISO-4217 currency code.


            More information:


            Maximum length: 16 characters'
        quotePrice:
          type: number
          description: 'The exchange rate used when a currency conversion between
            settlement currency and transaction currency occurs.


            More information:


            Value range: 1 - unlimited'
        quoteStartTime:
          type: string
          description: "The effective time of the exchange rate. \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
        quoteExpiryTime:
          type: string
          description: "The expiration time of the exchange rate. \n\nMore information:\n\
            \nThe value follows the ISO 8601 standard format. For example, \"2019-11-27T12:01:01+08:00\"\
            ."
        guaranteed:
          type: boolean
          description: Guaranteed exchange rate available for payment.
      required:
      - quoteCurrencyPair
      - quotePrice
    AcquirerInfo:
      acquirerMerchantName:
        type: string
        description: 收单方商户名称
      type: object
      properties:
        acquirerName:
          type: string
          description: "The name of the acquirer. \n\nNote: This parameter is returned\
            \ if you integrate the APO product.  \n\nMore information:\n\nMaximum\
            \ length: 64 characters"
        referenceRequestId:
          type: string
          description: "The unique ID that is assigned by APO to identify a payment\
            \ request sent to the acquirer.\n\nNote: This parameter is returned if\
            \ you integrate the APO product.  \n\nMore information:\n\nMaximum length:\
            \ 64 characters"
        acquirerTransactionId:
          type: string
          description: "The unique ID that is assigned by the acquirer to identify\
            \ a transaction. \n\nNote: This parameter is returned if you integrate\
            \ the APO product.\n\nMore information:\n\nMaximum length: 64 characters"
        acquirerMerchantId:
          type: string
          description: "The unique ID that is assigned by the acquirer to identify\
            \ a merchant. \n\nNote: This parameter is returned if you integrate the\
            \ APO product.  \n\nMore information:\n\nMaximum length: 64 characters\n"
        acquirerResultCode:
          type: string
          description: "The acquirer's result code that indicates the transaction\
            \ process result.  \n\nNote: This parameter is returned if you integrate\
            \ the APO product.\n\nMore information:\n\nMaximum length: 64 characters"
        acquirerResultMessage:
          type: string
          description: "The result message that describes acquirerResultCode in detail.\
            \  \n\nNote: This parameter is returned if you integrate the APO product.\n\
            \nMore information:\n\nMaximum length: 64 characters"
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: 'Result code


            More information:


            Maximum length: 64 characters'
        resultStatus:
          $ref: '#/components/schemas/ResultStatusType'
          description: "Result status. Valid values are:  \n\nS: Indicates that the\
            \ result status is successful. \nF: Indicates that the result status is\
            \ failed. \nU: Indicates that the result status is unknown. \nMore information:\n\
            \nMaximum length: 1 character"
        resultMessage:
          type: string
          description: 'Result message


            More information:


            Maximum length: 256 characters

            '
      required:
      - resultCode
      - resultStatus
      - resultMessage
    ResultStatusType:
      type: string
      enum:
      - S
      - F
      - U
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/payments/inquiryRefund
  description: 正式环境
security: []
