---
openapi: 3.1.0
info:
  title: payments_cancel
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/payments/cancel:
    post:
      summary: cancel
      deprecated: false
      description: 'Use this API to get the cashier page address. After getting the
        cashier page address, you can redirect the user to the cashier page to make
        a payment.

        '
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayPayCancelRequest'
            example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayPayCancelResponse'
          headers: {}
      security: []
components:
  schemas:
    ResultStatusType:
      type: string
      enum:
      - S
      - F
      - U
    Result:
      type: object
      properties:
        applinkUrl:
          type: string
          description: The URL for deep linking to mobile apps
        normalUrl:
          type: string
          description: The standard web URL
        schemeUrl:
          type: string
          description: The URL for custom URL schemes
        resultCode:
          type: string
          description: 'The result code.


            More information:


            Maximum length: 64 characters'
        resultStatus:
          description: "The result status. Valid values are:  \n\nS: Indicates that\
            \ the result status is successful. \nF: Indicates that the result status\
            \ is failed. \nU: Indicates that the result status is unknown. "
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: 'The result message.


            More information:


            Maximum length: 256 characters'
          maxLength: 256
      required:
      - resultCode
      - resultStatus
    AlipayPayCancelRequest:
      type: object
      properties:
        paymentId:
          type: string
          description: 'The original payment ID of the payment request to be canceled,
            generated by Antom to uniquely identify the payment when the merchant
            initiates the original payment. paymentId and paymentRequestId cannot
            both be null. A one-to-one correspondence between paymentId and paymentRequestId
            exists.


            More information:


            Maximum length: 64 characters'
        paymentRequestId:
          type: string
          description: 'The original payment request ID of the payment request to
            be canceled, generated by the merchant to uniquely identify a payment
            request. paymentRequestId and paymentId cannot both be null. If both paymentRequestId
            and paymentId are provided, paymentId takes precedence.


            More information:


            Maximum length: 64 characters'
        merchantAccountId:
          type: string
          description: 'The unique ID to identify a merchant account.


            Note: Specify this parameter when you use a single client ID across multiple
            locations.


            More information:


            Maximum length: 32 characters'
    AlipayPayCancelResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
          description: Indicates whether this API is called successfully. If this
            API is successfully called, the payment is canceled successfully.
        paymentId:
          type: string
          description: "The unique ID that is assigned by Antom to identify a payment.\n\
            \nNote: This field is returned when the cancellation succeeds (the value\
            \ of result.resultStatus is S). \n\nMore information:\n\nMaximum length:\
            \ 64 characters"
        paymentRequestId:
          type: string
          description: "The unique ID that is assigned by a merchant to identify a\
            \ payment request. \n\nNote: This field is returned when the cancellation\
            \ succeeds (the value of result.resultStatus is S). \n\nMore information:\n\
            \nMaximum length: 64 characters"
        cancelTime:
          type: string
          description: 'The actual execution completion time of the payment cancellation
            process, which is the date and time when the payment cancellation succeeds.


            Note: This field is returned when the cancellation succeeds (the value
            of result.resultStatus is S).


            More information:


            The value follows the ISO 8601 standard format. For example, "2019-11-27T12:01:01+08:00".'
      required:
      - result
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/payments/cancel
  description: 正式环境
security: []
