components:
  schemas:
    AlipaySubscriptionCreateRequest:
      properties:
        env:
          $ref: '#/components/schemas/Env'
          description: 'Information about the environment where the order is placed,
            such as the device information.  '
        orderInfo:
          $ref: '#/components/schemas/OrderInfo'
          description: 'The order information for the subscription. This field is
            used for different purposes:


            During the payment process, this field is mainly used by Antom for risk
            control or anti-money laundering.

            After the payment is completed, this field is used for recording and reporting
            purposes such as purchase tracking and regulatory reporting. '
        paymentAmount:
          $ref: '#/components/schemas/Amount'
          description: 'The payment amount charged to the user per subscription period.  '
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
          description: The payment method that is used to collect the payment by the
            merchant or acquirer.
        paymentNotificationUrl:
          description: "The URL that is used to receive the payment result notification\
            \ for each subscription period.\n\nYou can also configure the subscription\
            \ notification URL in Antom Dashboard. If you specify this URL in both\
            \ this API and Antom Dashboard, the URL configured in the API takes precedence.\
            \  \n\nYou can only configure one subscription notification URL in Antom\
            \ Dashboard.\n\nMore information:\n\nMaximum length: 2048 characters\n"
          type: string
        periodRule:
          $ref: '#/components/schemas/PeriodRule'
          description: "The subscription period rule, used to define a subscription's\
            \ billing period. \n\n"
        settlementStrategy:
          $ref: '#/components/schemas/SettlementStrategy'
          description: 'The settlement strategy for the payment request. '
        subscriptionDescription:
          description: "The description of the subscription, used for displaying user\
            \ consumption records and other actions. \n\nMore information:\n\nMaximum\
            \ length: 256 characters"
          type: string
        subscriptionEndTime:
          description: "The date and time when the subscription ends.\n\nNote: Specify\
            \ this parameter when you want to designate the subscription end time.\
            \  \n\nMore information:\n\nThe value follows the ISO 8601 standard format.\
            \ For example, \"2019-11-27T12:01:01+08:00\".\n"
          type: string
        subscriptionExpiryTime:
          description: 'A specific date and time after which the created subscription
            expires. When the subscription expires, the order must be terminated.
            The default value of this parameter is 30 minutes after the subscription
            creation request is sent.


            Note: Specify this parameter if you want to designate the subscription
            creation expiration time. The specified payment expiration time must be
            less than 48 hours after the subscription request is sent.


            More information:


            The value follows the ISO 8601 standard format. For example, "2019-11-27T12:01:01+08:00".'
          type: string
        subscriptionNotificationUrl:
          description: "The URL that is used to receive the subscription result notification.\
            \ \n\nYou can also configure the subscription notification URL in Antom\
            \ Dashboard. If you specify this URL in both this API and Antom Dashboard,\
            \ the URL configured in the API takes precedence.  \n\nOnly one subscription\
            \ notification URL can be configured in Antom Dashboard.\n\nMore information:\n\
            \nMaximum length: 2048 characters"
          type: string
        subscriptionRedirectUrl:
          description: "The merchant page URL that the user is redirected to after\
            \ authorizing the subscription. \n\nMore information:\n\nMaximum length:\
            \ 2048 characters\n"
          type: string
        subscriptionRequestId:
          description: "The unique ID assigned by a merchant to identify a subscription\
            \ request. Antom uses this field for idempotency control.  \n\nMore information:\n\
            \nThis field is an API idempotency field.For subscription requests that\
            \ are initiated with the same value of subscriptionRequestId and reach\
            \ a final status of S or F, the same result is to be returned for the\
            \ request.\nMaximum length: 64 characters"
          type: string
        subscriptionStartTime:
          description: "The date and time when the subscription becomes active.  \n\
            \nMore information:\n\nThe value follows the ISO 8601 standard format.\
            \ For example, \"2019-11-27T12:01:01+08:00\".\n"
          type: string
        trials:
          description: "The list of trial information of a subscription.  \n\nNote:\
            \ Specify this parameter if the subscription includes any trial periods."
          items:
            $ref: '#/components/schemas/Trial'
          type: array
      required:
      - subscriptionRequestId
      - subscriptionDescription
      - subscriptionRedirectUrl
      - subscriptionStartTime
      - periodRule
      - paymentMethod
      - subscriptionNotificationUrl
      - paymentNotificationUrl
      - orderInfo
      - paymentAmount
      - settlementStrategy
      - env
      type: object
    AlipaySubscriptionCreateResponse:
      properties:
        appIdentifier:
          description: 'An Android package name, which is used for Android app to
            open a cashier page.


            Note: This field is returned when result.resultCode is S and terminalType
            is APP or WAP.


            More information:


            Maximum length: 128 characters'
          type: string
        applinkUrl:
          description: 'The URL that redirects users to open an app when the target
            app is installed, or to open a WAP page when the target app is not installed.
            For Android, the URL is a Native App Link. For iOS, the URL is a Universal
            Link.


            Note: When the value of result.resultCode is S, at least one of schemeUrl,
            applinkUrl, and normalUrl is to be returned.


            More information:


            Maximum length: 2048 characters'
          type: string
        normalUrl:
          description: 'The URL that redirects users to a WAP or Web page in the default
            browser or the embedded WebView.


            Note: When the value of result.resultCode is S, at least one of schemeUrl,
            applinkUrl, and normalUrl is to be returned.


            More information:


            Maximum length: 2048 characters'
          type: string
        result:
          $ref: '#/components/schemas/Result'
          description: 'Indicates whether this API is called successfully. If this
            API is successfully called, the subscription authorization URL is returned. '
        schemeUrl:
          description: 'The URL scheme that redirects users to open an app in an Android
            or iOS system when the target app is installed.


            Note: When the value of result.resultCode is S, at least one of schemeUrl,
            applinkUrl, and normalUrl is to be returned.


            More information:


            Maximum length: 2048 characters'
          type: string
      required:
      - result
      type: object
    Amount:
      properties:
        currency:
          description: "The transaction currency that is specified in the contract.\
            \ A 3-letter currency code that follows the ISO 4217 standard. \n\nMore\
            \ information:\n\nMaximum length: 3 characters"
          type: string
        value:
          description: 'The amount to charge as a positive integer in the smallest
            currency unit. (That is, 100 cents to charge $1.00, or 100 to charge JPY
            100, a 0-decimal currency).


            Note: For details about the smallest currency unit, see Smallest unit
            of the currency.


            More information:


            Value range: 1 - unlimited'
          type: string
      required:
      - currency
      - value
      type: object
    BrowserInfo:
      properties:
        acceptHeader:
          description: The accept header of the user's browser
          type: string
        javaEnabled:
          description: Indicates whether the user's browser is able to run Java
          type: boolean
        javaScriptEnabled:
          description: Indicates whether the user's browser is able to run Java
          type: boolean
        language:
          description: The language of the user's browser
          type: string
        userAgent:
          description: The user agent of the user's browser
          type: string
      type: object
    Env:
      properties:
        clientIp:
          description: Client IP address of the device.
          example: 127.0.0.1
          type: string
        deviceId:
          description: Device ID of the user.
          example: eYOIkvFpZzztgO0Yu6USdprBQZCWxDhiUAHCiK8K/cH9mT6wMaMO****
          type: string
        deviceLanguage:
          description: Device language of the user.
          example: zh_CN
          type: string
        envType:
          description: ''
          example: oootype
          type: string
        envType123:
          description: ''
          example: oootype
          type: string
        terminalType:
          $ref: '#/components/schemas/TerminalType'
          description: 'Terminal type used by the merchant. Valid values are:'
      type: object
    OrderInfo:
      properties:
        orderAmount:
          $ref: '#/components/schemas/Amount'
          description: 'The payment amount charged to the user per subscription period.  '
      type: object
    OsType:
      enum:
      - IOS
      - ANDROID
      type: string
    PaymentMethod:
      properties:
        customerId:
          type: string
        extendInfo:
          type: string
        paymentMethodId:
          description: 'The unique ID that is used to identify a payment method.


            Pass the corresponding token to this field when the user has a bound payment
            method.


            More information:


            Maximum length: 128 characters

            '
          type: string
        paymentMethodMetaData:
          additionalProperties:
            type: object
          properties: {}
          type: object
        paymentMethodType:
          description: "The payment method that is used to accept the subscription\
            \ payment. See Payment methods to check the valid values.  \n\nNote: Card\
            \ payment method is not currently supported when you work with Antom as\
            \ your acquirer.\n\nMore information:\n\nMaximum length: 64 characters"
          type: string
        requireIssuerAuthentication:
          type: boolean
      required:
      - paymentMethodType
      type: object
    PeriodRule:
      properties:
        periodCount:
          description: "The number of period types within one subscription period.\
            \ For example, if the value of periodType is MONTH and the value of periodCount\
            \ is 2, it means that the subscription period is two months.  \n\nMore\
            \ information:\n\nValue range: 1 - unlimited"
          type: integer
        periodType:
          description: "The subscription period type. Valid values are:\n\nYEAR: indicates\
            \ that the subscription period is measured in years. \nMONTH: indicates\
            \ that the subscription period is measured in months. \nWEEK: indicates\
            \ that the subscription period is measured in weeks. \nDAY: indicates\
            \ that the subscription period is measured in days.  \nMore information:\n\
            \nMaximum length: 20 characters"
          type: string
      required:
      - periodType
      - periodCount
      type: object
    Result:
      properties:
        resultCode:
          description: The result code.
          type: string
        resultMessage:
          description: The result message.
          type: string
        resultStatus:
          $ref: '#/components/schemas/ResultStatusType'
          description: "The result status. Valid values are:\n\nS: indicates that\
            \ the result status is successful.\nF: indicates that the result status\
            \ is failed. \nU: indicates that the result status is unknown. "
      required:
      - resultCode
      - resultStatus
      - resultMessage
      type: object
    ResultStatusType:
      enum:
      - S
      - F
      - U
      type:
      - string
      - 'null'
    SettlementStrategy:
      properties:
        settlementCurrency:
          description: "The ISO currency code of the currency that the merchant wants\
            \ to be settled against. The field is required if the merchant signed\
            \ up for multiple currencies to settle. \n\nMore information:\n\nMaximum\
            \ length: 3 characters"
          type: string
      type: object
    TerminalType:
      enum:
      - WEB
      - WAP
      - APP
      - MINI_APP
      type: string
    Trial:
      properties:
        trialAmount:
          $ref: '#/components/schemas/Amount'
          description: 'The payment amount charged to the user per subscription period.  '
        trialEndPeriod:
          description: 'The end subscription period of the trial. For example, if
            the trial ends at the third subscription period, specify this parameter
            as 3.


            Note: Specify this parameter if the end subscription period is different
            from the start subscription period. If you leave this parameter empty,
            the default value of this parameter is the same as the value of trialStartPeriod.


            More information:


            Value range: 1 - unlimited

            '
          type: integer
        trialStartPeriod:
          description: "The start subscription period of the trial. For example, if\
            \ the trial starts from the first subscription period, specify this parameter\
            \ as 1.  \n\nMore information:\n\nValue range: 1 - unlimited"
          type: integer
      required:
      - trialStartPeriod
      - trialAmount
      type: object
  securitySchemes: {}
info:
  description: ''
  title: subscriptions_create
  version: 1.0.0
openapi: 3.1.0
paths:
  /ams/api/v1/subscriptions/create:
    post:
      deprecated: false
      description: 'Use this API to get the cashier page address. After getting the
        cashier page address, you can redirect the user to the cashier page to make
        a payment.

        '
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipaySubscriptionCreateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipaySubscriptionCreateResponse'
          description: ''
          headers: {}
      security: []
      summary: create
      tags: []
security: []
servers:
- description: 正式环境
  url: https://open-sea-global.alipay.com/ams/api/v1/subscriptions/create
tags: []
