openapi: 3.1.0
info:
  title: /ams/v1/subscriptions/inquiry
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/v1/subscriptions/inquiry:
    post:
      summary: subscriptions/inquiry
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipaySubscriptionsInquiryRequest'
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipaySubscriptionsInquiryResponse'
          headers: {}
      security: []
webhooks: {}
components:
  schemas:
    AlipaySubscriptionsInquiryRequest:
      type: object
      properties:
        subscriptionId:
          type: string
        subscriptionRequestId:
          type: string
    PeriodType:
      type: string
      enum:
        - WEEK
        - MONTH
        - QUARTER
        - HALF_YEAR
        - YEAR
      description: >-
        The subscription period type. Valid values are:

        WEEK: indicates that the subscription period is measured in weeks.

        MONTH: indicates that the subscription period is measured in months.

        QUARTER: indicates that the subscription period is measured in
        quarters.

        HALF_YEAR: indicates that the subscription period is measured in half
        years.

        YEAR: indicates that the subscription period is measured in years.
    PeriodRule:
      type: object
      properties:
        periodType:
          type: string
          description: >-
            The subscription period type.

            More information:

            Maximum length: 20 characters
        period:
          type: integer
          description: Number of periods
        price: &ref_0
          description: Amount for each period
          $ref: '#/components/schemas/Amount'
        periodCount:
          type: integer
          description: >-
            The number of period types within one subscription period. For
            example, if the value of periodType is MONTH and the value of
            periodCount is 2, it means that the subscription period is two
            months.  


            More information:


            Value range: 1 - unlimited
      required:
        - periodType
        - periodCount
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: |-
            The 3-letter currency code that follows the ISO 4217 standard. 

            More information:

            Maximum length: 3 characters
        value:
          type: string
          description: >
            The value of the amount as a positive integer in the smallest
            currency unit. For example, if the currency is USD and the amount is
            $1.00, set the value of this parameter to 100; or if the currency is
            JPY and the amount is ￥1, set the value of this parameter to 1.  


            For details about the smallest currency unit, see Smallest unit of
            the currency .


            For details about the minimum payment amount allowed for each
            payment method, see Minimum amount rules. 


            Note: Due to the currency practices in Indonesia, when the currency
            is IDR, round the amount with banker's rounding and fix the last two
            digits of this parameter as 00.  


            More information:


            Value range: 0 - unlimited
      required:
        - currency
        - value
    AlipaySubscriptionsInquiryResponse:
      type: object
      properties:
        allowRetry:
          type: string
        maxAmountFloor: *ref_0
        paymentAmount: *ref_0
        periodRule:
          $ref: '#/components/schemas/PeriodRule'
        subscriptionEndTime:
          type: string
        subscriptionRequestId:
          type: string
        subscriptionStartTime:
          type: string
        subscriptionStatus:
          type: string
        result:
          $ref: '#/components/schemas/Result'
      required:
        - result
    ResultStatusType:
      type: string
      enum:
        - S
        - F
        - U
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: |-
            The result status. Valid values are:

            S: indicates that the result status is successful.
            F: indicates that the result status is failed. 
            U: indicates that the result status is unknown. 
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: The result message.
      required:
        - resultCode
        - resultStatus
  securitySchemes: {}
servers:
  - url: https://open-sea-global.alipay.com/ams/api/v1/subscriptions/inquiry