openapi: 3.1.0
info:
  title: payments_supplyDefenseDocument
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/payments/supplyDefenseDocument:
    post:
      summary: supplyDefenseDocument
      deprecated: false
      description: >
        Use this API to get the cashier page address. After getting the cashier
        page address, you can redirect the user to the cashier page to make a
        payment.
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipaySupplyDefenseDocumentRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipaySupplyDefenseDocumentResponse'
          headers: {}
      security: []
components:
  schemas:
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: The result code.
        resultStatus:
          description: |-
            The result status. Valid values are:

            S: indicates that the result status is successful.
            F: indicates that the result status is failed. 
            U: indicates that the result status is unknown. 
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: The result message.
      required:
        - resultCode
        - resultStatus
        - resultMessage
    ResultStatusType:
      type:
        - string
        - 'null'
      enum:
        - S
        - F
        - U
    AlipaySupplyDefenseDocumentRequest:
      type: object
      properties:
        disputeId:
          type: string
          description: |-
            The unique ID assigned by Antom to identify a dispute.

            More information:

            Maximum length: 64 characters
        disputeEvidence:
          type: string
          description: >-
            The dispute defense document that you prepare for defending the
            dispute, which is encoded in the Base64 format.


            More information:


            Maximum length: 1000000 characters
      required:
        - disputeId
        - disputeEvidence
    AlipaySupplyDefenseDocumentResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Result'
          description: The result of the API call.
        disputeId:
          type: string
          description: >-
            The unique ID assigned by Antom to identify a dispute.


            Note: This prameter is returned when the value of resultCode is
            SUCCESS.


            More information:


            Maximum length: 64 characters
        disputeResolutionTime:
          type: string
          description: >-
            The time when you upload the dispute defense document.


            Note: This prameter is returned when the value of resultCode is
            SUCCESS.


            More information:


            Maximum length: 64 characters
      required:
        - result
  securitySchemes: {}
servers:
  - url: >-
      https://open-sea-global.alipay.com/ams/api/v1/payments/supplyDefenseDocument
    description: 正式环境
security: []
