components:
  schemas:
    Address:
      properties:
        address1:
          description: "Address line 1, for example, the street address, PO box, and\
            \ company name. \n\nMore information:\n\nMaximum length: 256 characters"
          type: string
        address2:
          description: "Address line 2, for example, the apartment, suite, unit, and\
            \ building information. \n\nMore information:\n\nMaximum length: 256 characters"
          type: string
        city:
          description: "The city, district, suburb, town, or village name. \n\nMore\
            \ information:\n\nMaximum length: 32 characters\n"
          type: string
        label:
          type: string
        region:
          description: "The 2-letter country or region code. For more information,\
            \ see the ISO 3166 Country Codes standard. \n\nMore information:\n\nMaximum\
            \ length: 2 characters"
          type: string
        state:
          description: "The state, country, or province name. \n\nFor card payments,\
            \ if your business entity is in the United States, and the card issuing\
            \ country is Canada, the United States, or the United Kingdom, set the\
            \ value to a region code that consists of two to three characters and\
            \ follows the ISO 3166-2 standard. \n\nMore information:\n\nMaximum length:\
            \ 8 characters"
          type: string
        zipCode:
          description: "The ZIP or postal code. \n\nFor card payments, if your business\
            \ entity is in the United States, specify this parameter according to\
            \ the following parameter value requirements:\n\nOnly contains numbers,\
            \ letters, hyphens, and spaces.\nMust be within ten characters. \nMore\
            \ information:\n\nMaximum length: 32 characters"
          type: string
      required:
      - region
      type: object
    AlipayVaultingPaymentMethodRequest:
      properties:
        customizedInfo:
          $ref: '#/components/schemas/CustomizedInfo'
        env:
          $ref: '#/components/schemas/Env'
          description: 'Information about the environment where the order is placed,
            such as the device information.  '
        merchantAccountId:
          type: string
        merchantRegion:
          description: "The country or region where the merchant operates the business.\
            \ The value of this parameter is a 2-letter country or region code based\
            \ on the ISO 3166 Country Codes standard. \n\nSome possible values are\
            \ US, SG, HK, PK, JP, CN, BR, AU, and MY.\n\nNote: Specify this parameter\
            \ when you use the Global Acquirer Gateway (GAGW) product.\n\nMore information:\n\
            \nMaximum length: 2 characters"
          type: string
        paymentMethodDetail:
          $ref: '#/components/schemas/PaymentMethodDetail'
          description: "The details about the payment method that needs to be vaulted.\
            \ \n\n"
        redirectUrl:
          description: 'The merchant page URL that the buyer is redirected to after
            the vaulting process is completed.


            More information:


            Maximum length: 2048 characters

            '
          type: string
        vaultingCurrency:
          type: string
        vaultingNotificationUrl:
          description: "The URL that is used to receive the vaulting result notification.\
            \ \n\nMore information:\n\nMaximum length: 2048 characters"
          type: string
        vaultingRequestId:
          description: "The unique ID that is assigned by a merchant to identify a\
            \ card vaulting request. \n\nMore information:\n\nThis field is an API\
            \ idempotency field.For vaulting requests that are initiated with the\
            \ same value of vaultingRequestId and reach a final status of S or F,\
            \ the same result is to be returned for the request.\nMaximum length:\
            \ 64 characters"
          type: string
      required:
      - vaultingRequestId
      - vaultingNotificationUrl
      - redirectUrl
      - paymentMethodDetail
      - env
      type: object
    AlipayVaultingPaymentMethodResponse:
      properties:
        applinkUrl:
          description: 'The URL that redirects the user to open an app when the target
            app is installed, or to open a WAP page when the target app is not installed.


            More information:


            Maximum length: 2048 characters'
          type: string
        normalUrl:
          description: "The URL that redirects the user to a WAP or WEB page in the\
            \ default browser or the embedded WebView.\n\nNote:\n\nWhen the value\
            \ of result.resultCode is VERIFICATION_IN_PROCESS, one or more of the\
            \ following URLs may be returned: schemeUrl, appLinkUrl, and normalUrl.\n\
            When the value of paymentMethodType is CARD, the user is required to complete\
            \ the 3DS authentication on the page accessed through this URL.  \nMore\
            \ information:\n\nMaximum length: 2048 characters"
          type: string
        paymentMethodDetail:
          $ref: '#/components/schemas/PaymentMethodDetail'
          description: "The details about the payment method that needs to be vaulted.\
            \ \n\n"
        result:
          $ref: '#/components/schemas/Result'
          description: 'The result of the API call. '
        schemeUrl:
          description: 'The URL scheme that redirects the user to open an app in an
            Android or iOS system when the target app is installed.


            More information:


            Maximum length: 2048 characters'
          type: string
        vaultingRequestId:
          description: "The unique ID that is assigned by a merchant to identify a\
            \ card vaulting request.  \n\nMore information:\n\nMaximum length: 64\
            \ characters"
          type: string
      required:
      - result
      - vaultingRequestId
      type: object
    Amount:
      properties:
        currency:
          type: string
        value:
          type: string
      required:
      - currency
      - value
      type: object
    BrowserInfo:
      properties:
        acceptHeader:
          description: The accept header of the user's browser
          type: string
        javaEnabled:
          description: Indicates whether the user's browser is able to run Java
          type: boolean
        javaScriptEnabled:
          description: Indicates whether the user's browser is able to run Java
          type: boolean
        language:
          description: The language of the user's browser
          type: string
        userAgent:
          description: The user agent of the user's browser
          type: string
      type: object
    CardBrand:
      enum:
      - VISA
      - MASTERCARD
      - MAESTRO
      - AMEX
      - JCB
      - DINERS
      - DISCOVER
      - CUP
      - MIR
      - ELO
      - HIPERCARD
      - TROY
      type: string
    CardPaymentMethodDetail:
      properties:
        authenticationFlow:
          type: string
        avsResultRaw:
          type: string
        billingAddress:
          $ref: '#/components/schemas/Address'
          description: "The billing address that is associated with the cardholder's\
            \ card account. \n\nNote: Specify this parameter if you require risk control.\
            \ Providing this information helps to increase the accuracy of anti-money\
            \ laundering and fraud detection, and increase payment success rates."
        bin:
          type: string
        brand:
          $ref: '#/components/schemas/CardBrand'
          description: Deprecated. Use selectedCardBrand instead.
        businessNo:
          description: 'The business number of the company that holds the corporate
            card. The value of this parameter is a 10-digit business number, such
            as 97XXXXXX11.


            Specify this parameter when all the following conditions are met:


            The card issuing bank is in Korea.

            The card is a corporate card.

            More information:


            Maximum length: 10 characters

            '
          type: string
        cardIssuer:
          type: string
        cardNo:
          description: "The card number. \n\nMore information:\n\nMaximum length:\
            \ 32 characters"
          type: string
        cardPasswordDigest:
          description: 'The first two digits of the card payment password.


            Note: Specify this parameter when the card issuing bank is in Korea.


            More information:


            Maximum length: 2 characters

            '
          type: string
        cardToken:
          description: "The token of the card. The value of this parameter is used\
            \ by paymentMethodId in the pay (Checkout Payment) API when initiating\
            \ payments. \n\nMore information:\n\nMaximum length: 2048 characters"
          type: string
        cardholderName:
          $ref: '#/components/schemas/UserName'
        countryIssue:
          type: string
        cpf:
          description: 'The Cadastro Pessoal de Pessoa Física (CPF) is the tax ID
            of the Brazilian individual taxpayer.


            Note: Specify this parameter when the card issuing bank is in Brazil.


            More information:


            Maximum length: 11 characters'
          type: string
        cvv:
          description: "The card verification value (CVV), which is also known as\
            \ a card security code (CSC) or a card verification code (CVC). \n\nNote:\
            \ Specify this parameter when the card issuing bank is in Brazil, Chile,\
            \ Mexico, or Peru, or the card is a global card.\n\nMore information:\n\
            \nMaximum length: 3 characters"
          type: string
        cvvResultRaw:
          type: string
        dateOfBirth:
          description: 'The date of birth of the cardholder. The value of this parameter
            is an 8-digit date of birth in the format of YYYY-MM-DD that follows the
            ISO 8601 standard. For example, 1971-06-07 means the cardholder''s birthday
            is June 7, 1971.


            Specify this parameter when all the following conditions are met:


            The card issuing bank is in Korea.

            The card is a personal card.

            More information:


            Maximum length: 10 characters'
          type: string
        enableAuthenticationUpgrade:
          type: string
        expiryMonth:
          description: "The month the card expires. Pass in two digits representing\
            \ the month. For example, if the expiration month is February, the value\
            \ of this parameter is 02. \n\nMore information:\n\nMaximum length: 2\
            \ characters"
          type: string
        expiryYear:
          description: "The year the card expires. Pass in the last two digits of\
            \ the year number. For example, if the expiration year is 2025, the value\
            \ of this parameter is 25. \n\nMore information:\n\nMaximum length: 2\
            \ characters"
          type: string
        fingerprint:
          type: string
        funding:
          type: string
        instUserName:
          $ref: '#/components/schemas/UserName'
        is3DSAuthentication:
          description: 'Indicates whether the transaction authentication type is 3D
            secure. Specify this parameter when the value of paymentMethodType is
            CARD.


            '
          type: boolean
        issuerName:
          type: string
        issuingCountry:
          type: string
        last4:
          type: string
        lastFour:
          type: string
        mask:
          type: string
        maskedCardNo:
          description: "The masked card number, showing only a few digits and hiding\
            \ the rest. \n\nMore information:\n\nMaximum length: 64 characters"
          type: string
        mpiData:
          $ref: '#/components/schemas/MpiData'
        networkTransactionId:
          type: string
        payerEmail:
          description: "The email address of the payer. \n\nNote: Specify this parameter\
            \ when the card issuing bank is in Brazil, Chile, Mexico, or Peru.\n\n\
            More information:\n\nMaximum length: 64 characters\n"
          type: string
        paymentMethodDetailMetadata:
          type: string
        request3DS:
          type: string
        scaExemptionIndicator:
          type: string
        selectedCardBrand:
          $ref: '#/components/schemas/CardBrand'
          description: Deprecated. Use selectedCardBrand instead.
      required:
      - expiryYear
      - expiryMonth
      type: object
    CouponPaymentMethodDetail:
      properties:
        availableAmount:
          $ref: '#/components/schemas/Amount'
        couponDescription:
          type: string
        couponExpireTime:
          type: string
        couponId:
          type: string
        couponName:
          type: string
        paymentMethodDetailMetadata:
          type: string
      type: object
    CustomizedInfo:
      properties:
        customizedField1:
          type: string
        customizedField2:
          type: string
        customizedField3:
          type: string
        customizedField4:
          type: string
        customizedField5:
          type: string
      type: object
    DiscountPaymentMethodDetail:
      properties:
        availableAmount:
          $ref: '#/components/schemas/Amount'
        discountDescription:
          type: string
        discountId:
          type: string
        discountName:
          type: string
        paymentMethodDetailMetadata:
          type: string
      type: object
    Env:
      properties:
        clientIp:
          description: Client IP address of the device.
          example: 127.0.0.1
          type: string
        deviceId:
          description: Device ID of the user.
          example: eYOIkvFpZzztgO0Yu6USdprBQZCWxDhiUAHCiK8K/cH9mT6wMaMO****
          type: string
        deviceLanguage:
          description: Device language of the user.
          example: zh_CN
          type: string
        envType:
          description: ''
          example: oootype
          type: string
        terminalType:
          $ref: '#/components/schemas/TerminalType'
          description: 'Terminal type used by the merchant. Valid values are:'
      type: object
    ExternalPaymentMethodDetail:
      properties:
        accountDisplayName:
          type: string
        assetToken:
          type: string
        disableReason:
          type: string
        paymentMethodDetailMetadata:
          type: string
      type: object
    MpiData:
      properties:
        cavv:
          type: string
        dsTransactionId:
          type: string
        eci:
          type: string
        threeDSVersion:
          type: string
      type: object
    OsType:
      enum:
      - IOS
      - ANDROID
      type: string
    PaymentMethodDetail:
      properties:
        card:
          $ref: '#/components/schemas/CardPaymentMethodDetail'
          description: "The card information. \n\nSpecify this parameter when all\
            \ the following conditions are met:\n\nYou are PCI compliant.\nThe value\
            \ of paymentMethodType is CARD."
        coupon:
          $ref: '#/components/schemas/CouponPaymentMethodDetail'
        discount:
          $ref: '#/components/schemas/DiscountPaymentMethodDetail'
        extendInfo:
          type: string
        externalAccount:
          $ref: '#/components/schemas/ExternalPaymentMethodDetail'
        interactionType:
          type: string
        paymentMethodDetailType:
          $ref: '#/components/schemas/PaymentMethodDetailType'
        paymentMethodType:
          description: "The type of payment method to be vaulted. The value of this\
            \ parameter is fixed to CARD.  \n\nMore information:\n\nMaximum length:\
            \ 64 characters"
          type: string
        wallet:
          $ref: '#/components/schemas/Wallet'
      required:
      - paymentMethodType
      type: object
    PaymentMethodDetailType:
      enum:
      - CARD
      - EXTERNALACCOUNT
      - COUPON
      - DISCOUNT
      type: string
    Result:
      properties:
        resultCode:
          description: The result code.
          type: string
        resultMessage:
          description: The result message.
          type: string
        resultStatus:
          $ref: '#/components/schemas/ResultStatusType'
          description: "The result status. Valid values are:\nS: indicates that the\
            \ result status is successful.\nF: indicates that the result status is\
            \ failed. \nU: indicates that the result status is unknown. "
      required:
      - resultCode
      - resultStatus
      - resultMessage
      type: object
    ResultStatusType:
      enum:
      - S
      - F
      - U
      type:
      - string
      - 'null'
    TerminalType:
      enum:
      - WEB
      - WAP
      - APP
      - MINI_APP
      type: string
    UserName:
      properties:
        firstName:
          description: "The cardholder's first name. \n\nMore information:\n\nMaximum\
            \ length: 32 characters\n"
          type: string
        fullName:
          description: "The cardholder's full name. \n\nMore information:\n\nMaximum\
            \ length: 128 characters"
          type: string
        lastName:
          description: 'The cardholder''s last name. '
          type: string
        middleName:
          description: "The cardholder's middle name. \n\nMore information:\n\nMaximum\
            \ length: 32 characters"
          type: string
      required:
      - firstName
      - lastName
      type: object
    Wallet:
      properties:
        accountHolderName:
          $ref: '#/components/schemas/UserName'
        accountNo:
          type: string
        billingAddress:
          $ref: '#/components/schemas/Address'
          description: "The billing address that is associated with the cardholder's\
            \ card account. \n\nNote: Specify this parameter if you require risk control.\
            \ Providing this information helps to increase the accuracy of anti-money\
            \ laundering and fraud detection, and increase payment success rates."
        email:
          type: string
        phoneNo:
          type: string
      type: object
  securitySchemes: {}
info:
  description: ''
  title: vaults_vaultPaymentMethod
  version: 1.0.0
openapi: 3.1.0
paths:
  /ams/api/v1/vaults/vaultPaymentMethod:
    post:
      deprecated: false
      description: 'Use this API to get the cashier page address. After getting the
        cashier page address, you can redirect the user to the cashier page to make
        a payment.

        '
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayVaultingPaymentMethodRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayVaultingPaymentMethodResponse'
          description: ''
          headers: {}
      security: []
      summary: vaultPaymentMethod
      tags: []
security: []
servers:
- description: 正式环境
  url: https://open-sea-global.alipay.com/ams/api/v1/vaults/vaultPaymentMethod
tags: []
