openapi: 3.1.0
info:
  title: fetchNonce
  description: ''
  version: 1.0.0
tags: []
paths:
  /ams/api/v1/vaults/fetchNonce:
    post:
      summary: fetchNonce
      deprecated: false
      description: Use this API to collect card information when you do not have PCI
        qualifications.
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlipayVaultsFetchNonceRequest'
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlipayVaultsFetchNonceResponse'
          headers: {}
      security: []
webhooks: {}
components:
  schemas:
    Result:
      type: object
      properties:
        resultCode:
          type: string
          description: Result code. The result code that might be returned are listed
            in the Result/Error codes table on this page.
        resultStatus:
          description: "The result status. Valid values are:\n\nS: indicates that\
            \ the result status is successful.\nF: indicates that the result status\
            \ is failed. \nU: indicates that the result status is unknown. "
          $ref: '#/components/schemas/ResultStatusType'
        resultMessage:
          type: string
          description: Result message that explains the result code.
      required:
      - resultCode
      - resultStatus
      - resultMessage
    ResultStatusType:
      type: string
      enum:
      - S
      - F
      - U
    UserName:
      type: object
      properties:
        firstName:
          type: string
          description: 'The cardholder''s first name.


            More information:


            Maximum length: 32 characters'
        middleName:
          type: string
          description: 'Middle name


            More information:


            Maximum length: 32 characters'
        lastName:
          type: string
          description: 'The cardholder''s last name.


            More information:


            Maximum length: 32 characters'
        fullName:
          type: string
          description: 'Full name


            More information:


            Maximum length: 128 characters'
      required:
      - firstName
      - lastName
    Card:
      type: object
      properties:
        cardNo:
          type: string
          description: The card number.
        cvv:
          type: string
          description: The card verification value (CVV), which is also known as a
            card security code (CSC) or a card verification code (CVC).Specify this
            parameter when the value of paymentMethodRegion is GLOBAL, BR, CL, MX,
            or PE.
        expiryYear:
          type: string
          description: The year the card expires. Pass in the last two digits of the
            year number. For example, if the expiry year is 2025, the value of this
            parameter is ​25​.
        expiryMonth:
          type: string
          description: The month the card expires. Pass in two digits representing
            the month. For example, if the expiry month is February, the value of
            this parameter is ​02​.
        cardholderName:
          $ref: '#/components/schemas/UserName'
          description: 'The cardholder''s name.

            Specify this parameter when the value of paymentMethodRegion is BR, CL,
            MX, or PE.'
      required:
      - cardNo
      - expiryYear
      - expiryMonth
    AlipayVaultsFetchNonceRequest:
      type: object
      properties:
        card:
          $ref: '#/components/schemas/Card'
          description: The card information.
      required:
      - card
    AlipayVaultsFetchNonceResponse:
      type: object
      properties:
        cardToken:
          type: string
          description: The token of the card. The value of this parameter is used
            by paymentMethodId in the pay (One-time Payments) API when initiating
            payments.
        result:
          $ref: '#/components/schemas/Result'
          description: The result of the API call.
      required:
      - cardToken
      - result
  securitySchemes: {}
servers:
- url: https://open-sea-global.alipay.com/ams/api/v1/vaults/fetchNonce
