name: Notify libraries

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
    steps:
      - name: SDK Automation
        run: gh workflow run gradle.yml -R wangzunjiao/antom-sdk-automation
